kadena-io/chainweb-node

chainweb.cabal, test/Chainweb/Test/Pact/Utils.hs
Low-priority PR
- utility for making transaction JSON in GHCI
- some cleanup to show failures in other test transaction makers.
=> Transaction maker utility

examples/P2pExample.hs, src/Chainweb/Chainweb/ChainResources.hs, src/Chainweb/CutDB.hs, src/Chainweb/CutDB/Sync.hs, src/Chainweb/Sync/WebBlockHeaderStore/Test.hs, src/Chainweb/Utils/Paging.hs, src/Data/CAS.hs, src/P2P/Node.hs, src/P2P/Session.hs, src/P2P/TaskQueue.hs, src/P2P/TaskQueue/Test.hs
=> faster consensus catchup

stack.yaml
=> Stack: Pin newest YAML

examples/TransactionGenerator.hs
Initial ground work for my planned TXG functionality extensions, which I need to testing Pact transaction throughput on the network.
=> TXG Spruce Up

src/Chainweb/BlockHeader.hs, src/Chainweb/Miner/POW.hs, src/Chainweb/Miner/Test.hs
This PR expands on information sent to our logging backends when mining is successful.
=> Initial Pact Transaction Statistics

src/Utils/Logging.hs
Implement the convention that Elasticsearch index names are suffixed with the date and a new index is created each day.
The implementation makes a `HEAD` call for the index before submitting a new `_bulk` POST requests to an Elasticsearch index. If the `HEAD` call fails a new index is created.
=> Create per-day Elasticsearch indices

.gitignore, chainweb.cabal, default.nix, examples/Chainweb/Simulate/Contracts/CoinContract.hs, examples/Chainweb/Simulate/Contracts/SimplePayments.hs, examples/Chainweb/Simulate/Utils.hs, examples/TransactionGenerator.hs, exe/CwTool.hs, stack.yaml
This PR changes the behaviour of the Transaction Generator, such that it sends requests to all available chains in an even way (round-robin). Eventually  more schemes could be added.
It also reworks certain logging logic.
=> TGX: Round-robin Chain Selection

src/Chainweb/Mempool/InMem.hs, src/Chainweb/Mempool/Mempool.hs, src/Chainweb/Mempool/RestAPI/Client.hs, src/Chainweb/Mempool/Socket.hs
to make investigating mempool stuff not a complete nightmare
=> explicit mempool constructor cleanup

src/Chainweb/Chainweb/ChainResources.hs, src/Chainweb/Mempool/Mempool.hs, test/Chainweb/Test/Mempool/Sync.hs
PR #201 caused a large slow-down in the mempool sync tests. This speeds up the mempool sync tests again.
=> add parameter to configure mempool synchronization interval

src/Chainweb/BlockHeader.hs, src/Chainweb/Miner/POW.hs, src/Chainweb/Miner/Test.hs
An `Int` of the raw count of bytes.
=> Log Payload Sizes

cabal.project, default.nix, stack.yaml
=> Upgraded pact

cabal.project, default.nix, stack.yaml
=> Pact fb30307

src/Chainweb/BlockHeader.hs, src/Chainweb/Miner/POW.hs, src/Chainweb/Miner/Test.hs
For logging the overall hash power of the network.
=> Count Hash Attempts

src/Chainweb/BlockHeader.hs, src/Chainweb/Miner/POW.hs, src/Chainweb/Time.hs
It's an estimate based on the time it took to mine the block. Once this is deployed, I'll produce a nice timeseries.
=> Log per-chain Network Hash Power

chainweb.cabal, default.nix, stack.yaml
This should enable more compatibility with `tls-1.5`.
=> warp-tls 3.2.7

.gitlab-ci.yml
Part of the ongoing CI improvement work.
=> Temporarily disable Mac CI

default.nix, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/SPV.hs
=> Note Nondeterministic Tests + Shut off 'hide-successes'

src/Chainweb/Logging/Config.hs, src/Chainweb/Utils.hs
=> Validation for EnableConfig values

.gitlab-ci.yml, chainweb.cabal, default.nix, stack.yaml
This is to relieve strain on our CI machines.
Also does some weeding / dep version bumps.
=> Less Concurrent Tests

chainweb.cabal, miner/Miner.hs, src/Chainweb/Miner/Core.hs, src/Chainweb/Miner/POW.hs, test/Chainweb/Test/Pact/PactReplay.hs
This PR moves the mining "inner loop" code into a library module, and then shares it between the built-in and stand-alone miners.
This is part of the on-going Mining Client work.
=> Mining Inner Loop

test/ChainwebTests.hs
And now the prodigal test returns!
=> Pact Replay returns

chainweb.cabal, src/Chainweb/Miner.hs, src/Chainweb/Miner/Config.hs, src/Chainweb/Miner/Pact.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Service/BlockValidation.hs, src/Chainweb/Pact/Service/Types.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Pact/Types.hs, src/Chainweb/WebPactExecutionService.hs, src/Chainweb/WebPactExecutionService/Types.hs, test/Chainweb/Test/CoinContract.hs, test/Chainweb/Test/CutDB.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/PactInProcApi.hs, test/Chainweb/Test/Pact/PactReplay.hs, test/Chainweb/Test/Pact/Utils.hs, tools/ea/Ea.hs
After a discussion with @emilypi .
=> Miner Module Reorg

src/Chainweb/Difficulty.hs, test/Chainweb/Test/Roundtrips.hs
This PR fixes a sneaky bug that occurs occasionally during Early DA.
=> Tommy, stop dividing by zero, you know your father hates that.

src/Chainweb/Chainweb/ChainResources.hs, src/Chainweb/Mempool/InMem.hs, src/Chainweb/Mempool/InMemTypes.hs
This PR provides to quick-and-dirty patches for the mempool that improve performance and debugability. 
Both should be improved in follow up PRs
=> Mempool telemetry and bound

src/Chainweb/Pact/PactService.hs
Earlier assumption was that gas limit was denominated in coin -- however this
was incorrect, we should do the balance check using `(gas price * gas limit)`
denominated in coin.
Fixes #392
=> Fix coin balance gas limit check.

cabal.project, default.nix, stack.yaml
This will ease the transition to newer package sets.
=> Mega Neat Pact

chainweb.cabal, src/Chainweb/Miner/Core.hs, src/Chainweb/PowHash.hs
You've all been waiting for it.
=> The True PoW Hash

miner/README.org
=> Corrections to Mining Guide

miner/Miner.hs, src/Chainweb/BlockHeader.hs
```
2019-09-17 10:39:10.309575: [info] Chain 4: Mined block at Height 2876.
```
=> Mining: Report `BlockHeight` on Success

miner/README.org
It was just a... *minor* typo.
=> Typo in Miner Guide

src/Chainweb/Chainweb/MinerResources.hs, src/Chainweb/Time.hs
This prevents an eventual memory buildup.
=> Pruning the Mining Coordination State

node/ChainwebNode.hs, src/Chainweb/BlockHeader.hs, src/Chainweb/Chainweb/MinerResources.hs, src/Chainweb/Miner/Coordinator.hs, src/Chainweb/Miner/RestAPI/Server.hs
This PR helps us monitor Mining Coordination activity.
=> MiningState Statistics

src/Chainweb/Chainweb/MinerResources.hs
=> Avoid divide-by-zero error

miner/Miner.hs, miner/README.org
Preemption messages are now reduced to `Debug`.
=> Shush Miner

cabal.project, src/Chainweb/BlockHeaderDB/RestAPI/Client.hs, src/Chainweb/Chainweb/ChainResources.hs, src/Chainweb/Chainweb/CutResources.hs, src/Chainweb/CutDB/Sync.hs, src/Chainweb/Mempool/InMem.hs, src/Chainweb/Mempool/RestAPI.hs, src/Chainweb/Mempool/RestAPI/Client.hs, src/Chainweb/Mempool/RestAPI/Server.hs, src/Chainweb/Miner/Coordinator.hs, src/Chainweb/Pact/RestAPI/Server.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Payload/RestAPI/Server.hs, src/Chainweb/RestAPI/Orphans.hs, src/Chainweb/Sync/WebBlockHeaderStore/Types.hs, src/Chainweb/Transaction.hs, src/Chainweb/TreeDB.hs, src/Chainweb/Utils.hs, src/Network/X509/SelfSigned.hs, test/Chainweb/Test/Mempool.hs, test/Chainweb/Test/Mempool/RestAPI.hs, test/Chainweb/Test/Pact/ChainData.hs, test/Chainweb/Test/Pact/Checkpointer.hs, test/Chainweb/Test/Pact/PactReplay.hs, test/Chainweb/Test/Pact/Utils.hs, tools/chain2gexf/Chain2Gexf.hs, tools/standalone/Standalone/Utils.hs
A set of changes form my `git stash` stack that were too small to justify individual PRs.
=> Miscellaneous fixes and cleanups

src/Chainweb/Utils.hs
The improved version doesn't allocate so it should be faster.
=> Improve leadingZeros

src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Service/BlockValidation.hs, src/Chainweb/Pact/Service/PactInProcApi.hs, src/Chainweb/Pact/Service/PactQueue.hs, src/Chainweb/WebPactExecutionService.hs, test/Chainweb/Test/Pact/ChainData.hs, test/Chainweb/Test/Pact/PactInProcApi.hs, test/Chainweb/Test/Pact/PactReplay.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/TTL.hs, test/Chainweb/Test/Pact/Utils.hs, test/Chainweb/Test/Utils.hs, tools/txg/TXG.hs
=> Use bounded queue for pact service

project.nix
The old one is broken with recent nix versions
=> Use newer gitignore infrastructure

miner/Miner.hs, stack.yaml
This PR smooths the results of `chainweb-miner`'s reported hash rate in a way compatible with both CPU and GPU mining.
=> Amortized Hash Reporting

miner/Miner.hs
=> Avoid div-by-zero

miner/Miner.hs
This PR also introduces a delay between attempts to connect to the update stream.
=> More Miner Logging

.github/workflows/applications.yml
Before merging to master, the `on` entry for this branch should be removed.
=> add ubuntu-16.04 build

src/Chainweb/CutDB/Sync.hs
This logging hick-up caused a lot of confusion ...
=> [BUG] fix logging of received cuts

CHANGELOG.md, src/Chainweb/Chainweb.hs, src/Chainweb/Chainweb/CutResources.hs, src/Chainweb/CutDB.hs, test/Chainweb/Test/CutDB.hs, tools/genconf/GenConf.hs, tools/standalone/Standalone/Chainweb.hs
The various cut-related options now look like this:
```yaml
cuts:
includeOrigin: true
pruneChainDatabase: true
fetchTimeout: 3000000
initialCutHeightLimit: null
```
=> Consolidate Cut Config

tools/txg/TXG.hs
This is a small PR created so that the transaction generator code
reads better than it did before.
=> [TXG] Beautify REST API calls

src/Chainweb/Chainweb.hs, src/Chainweb/Chainweb/ChainResources.hs, src/Chainweb/Mempool/InMem.hs, src/Chainweb/Mempool/Mempool.hs, src/Chainweb/Mempool/RestAPI/Client.hs, src/Chainweb/Pact/Service/PactInProcApi.hs, test/Chainweb/Test/Mempool.hs, test/Chainweb/Test/Mempool/InMem.hs, test/Chainweb/Test/Mempool/RestAPI.hs, test/Chainweb/Test/Pact/Utils.hs, tools/standalone/Standalone/Chainweb.hs
Actually implements existing config. 
Need help from @gregorycollins on failing test
=> Configurable block gas limit (finally)

src/Chainweb/Pact/Backend/ForkingBench.hs
Benches now take the usual amount of time, and give consistent output
```
Benchmark bench: RUNNING...
benchmarking PactService/forkingBench
time                 2.917 s    (2.855 s .. 2.985 s)
1.000 R²   (1.000 R² .. 1.000 R²)
mean                 2.867 s    (2.840 s .. 2.892 s)
std dev              29.21 ms   (24.59 ms .. 31.64 ms)
variance introduced by outliers: 19% (moderately inflated)
benchmarking PactService/oneBlock[1]
time                 270.2 ms   (248.5 ms .. 304.5 ms)
0.994 R²   (0.987 R² .. 1.000 R²)
mean                 250.9 ms   (245.3 ms .. 261.1 ms)
std dev              10.27 ms   (2.364 ms .. 14.23 ms)
variance introduced by outliers: 16% (moderately inflated)
benchmarking PactService/oneBlock[10]
time                 305.6 ms   (300.7 ms .. 311.4 ms)
1.000 R²   (1.000 …
```
=> use `envWithCleanup` instead of `perRunEnvWithCleanup` for benches

chainweb.cabal, src/Chainweb/Miner/RestAPI/Server.hs
A simple error message change that's helpful for debugging.
=> Display Unauthorized Miner

chainweb.cabal, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Templates.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Pact/Types.hs, src/Chainweb/Version.hs, test/Chainweb/Test/CoinContract.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/Utils.hs
Reintroduces #749 to address #797
=> reintroduce precompilation

tools/txg/TXG.hs, tools/txg/TXG/Repl.hs, tools/txg/TXG/ReplInternals.hs, tools/txg/TXG/Simulate/Contracts/Common.hs, tools/txg/TXG/Types.hs
These items are now configurable
* `GasLimit`
* `GasPrice`
* `TTLSeconds`
=> [Transaction Generator] More configurable options

pact/coin-contract/v2/coin.pact, pact/coin-contract/v2/coin.repl, pact/coin-contract/v2/fungible-v1.pact
This is for diffing purposes in later PRs
=> Copy Coin Contract, Fungible V1 to New Location

src/Chainweb/Chainweb/MinerResources.hs, src/Chainweb/Miner/Coordinator.hs
Some extra debugging information for the new Primed Coordination.
=> Log size of primed work cache

chainweb.cabal, overrides.nix, stack.yaml
With a brand-new version of `warp`, this may solve our connection issues.
See also https://github.com/yesodweb/wai/issues/780
=> Up-pin wai/warp/servant

src/Chainweb/Pact/Backend/ChainwebPactDb.hs, test/Chainweb/Test/Pact/Checkpointer.hs
Pretty up error message in `handlePossibleRewind` and add a corresponding test.
=> [Checkpointer] Redo error messages

cabal.project, chainweb.cabal, project.nix, src/Chainweb/BlockHeader/Genesis.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Types.hs, src/Chainweb/Payload.hs, stack.yaml, test/Chainweb/Test/CutDB.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/RemotePactTest.hs
Now you get something like this:
```
{
"Left": {
"tag": "BlockValidationFailure",
"contents": {
"mismatch": {
"data": "Payload hash",
"actual": "wpxQE11l_3CJJv6L_herUWAfWVw34DGXMO_har0aC70",
"expected": "iiLRm1ruZpCwyRFpEkY181QdcukvLjjD8il5HMp8gOE"
},
"details": [
{
"outputs": {
"txs": [
{
"tx": {
"hash": "rGpoi9i_yHXxjCtO9sXvrvXLH5u7rz7pCyP_gFYY0UA",
"sigs": [
{
"sig": "2a10c3bb65aa86edcc7b7d4a15746e6c3824b48db22f65cb90f5b21c075247122d3709fe11170b8c7626352c76cf333db66011739103c291d6a0315aa32ae30f"
}
],
"cmd": {
"networkId": null,
"payload": {
"exec": {
"data": {},
"code": "(coin.transfer \"sender00\" \"sender01\" 1.0)"
}
},
"signers": [
{
"pubKey": "368820f80c324bbc7c2b0610688a7da43e39f91d118732671cd9c7500ff43cca"
}
],
"meta": {
"creationTime": 0,
"ttl": 1000000,
"gasLimit": 10000, …
```
=> Better payload block validation error output

chainweb.cabal, src/Chainweb/SPV/CreateProof.hs, src/Chainweb/TreeDB.hs, test/Chainweb/Test/SPV.hs
=> create minimal spv proofs by default

src/Chainweb/Chainweb.hs, tools/header-dump/HeaderDump.hs
=> Increase block gas limit

chainweb.cabal, overrides.nix, stack.yaml
This fixes a bug with HTTP/2 that affects certain endpoints.
=> Newest Warp

chainweb.cabal, overrides.nix, tools/header-dump/HeaderDump.hs
=> improve header-dump tool

src/Chainweb/Mempool/Mempool.hs, src/Chainweb/Pact/PactService.hs, test/Chainweb/Test/Pact/RemotePactTest.hs
Closes https://github.com/kadena-io/chainweb-node/issues/890
=> More detailed errors when attempt buy gas fails

test/Chainweb/Test/Mempool.hs
=> High Water Test

test/Chainweb/Test/Pact/SPV.hs
=> Mine an additional cut height in SPV tests

.gitignore, src/Chainweb/BlockHeaderDB.hs, src/Chainweb/BlockHeight.hs, src/Chainweb/BlockWeight.hs, src/Chainweb/Pact/Backend/Types.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Service/Types.hs, test/Chainweb/Test/Pact/ChainData.hs, test/Chainweb/Test/Pact/PactInProcApi.hs, test/Chainweb/Test/Pact/PactReplay.hs, test/Chainweb/Test/Pact/TTL.hs, test/Chainweb/Test/Pact/TransactionTests.hs, test/Chainweb/Test/Pact/Utils.hs, test/ChainwebTests.hs
Some code cleanup changes that have been accumulating while working on other PRs over the past days
=> Some accumulated code cleanup

CHANGELOG.md, chainweb.cabal, node/ChainwebNode.hs
=> version 1.6, changelog 

src/Chainweb/BlockHeader.hs, src/Chainweb/Pact/PactService.hs
This is the first PR in a series of PRs that factor out of #902 the non-forking parts that can be safely committed to master.
=> Pact service exceptions and useful instances for ParentBlockHeader and ParentCreationTime

src/Chainweb/BlockHeader.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Version.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/TransactionTests.hs, test/Chainweb/Test/Pact/Utils.hs, test/golden/create-accounts-expected.txt, test/golden/create-table-expected.txt, test/golden/transfer-accounts-expected.txt
Second PR in a series with the goal to reduce #902 to a minimal forking subset.
=> Replace date base coinbaseV2 guard by block height based guard

test/Chainweb/Test/Pact/RemotePactTest.hs
In my ghci sessions it took about 10 seconds until the first cut was mined. Once the first cut is available a large number of empty blocks was mined instantaneously.
This PR awaits a cut at height 100 before it starts to evaluate tests, eliminating possible corner cases and races during network startup.
=> Await chainweb initialization in pact remote test

cabal.project, project.nix, src/Chainweb/Chainweb.hs, src/Chainweb/Chainweb/ChainResources.hs, src/Chainweb/Pact/Backend/ForkingBench.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Service/PactInProcApi.hs, src/Chainweb/Pact/Service/Types.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Pact/Types.hs, stack.yaml, test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/Utils.hs, tools/ea/Ea.hs
Allows configuration to make direct table reads in local
=> Allow reads in local via config

node/ChainwebNode.hs, src/Chainweb/Logging/Amberdata.hs, src/Chainweb/Mempool/InMem.hs, src/Chainweb/Mempool/Mempool.hs, src/Chainweb/Miner/Miners.hs, src/Chainweb/Pact/Backend/ForkingBench.hs, test/Chainweb/Test/CutDB.hs, test/Chainweb/Test/Mempool.hs, test/Chainweb/Test/Mempool/Sync.hs, test/Chainweb/Test/Misc.hs, test/Chainweb/Test/MultiNode.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/PactInProcApi.hs, test/Chainweb/Test/Pact/PactReplay.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/SPV.hs, test/Chainweb/Test/Pact/TTL.hs, test/Chainweb/Test/Pact/Utils.hs, test/Chainweb/Test/Tools/TXGen.hs, test/ChainwebTests.hs, test/ChainwebToolsTests.hs
This helps with legibility of numeric constants.
=> Numeric Underscores

test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/Utils.hs, test/pact/continuation-gas-payer.pact
with `PactExec` moved over to them (even passing goldens!)
=> Better test utilities for building Pact commands

src/Chainweb/BlockHeader.hs
See https://github.com/kadena-io/chainweb-node/issues/954
=> Updated binary encoding for BlockHeader

README.md
Adding some keywords to fulfill trademark requirements for the Chainweb Trademark.
=> Update ReadMe for Trademark

src/Chainweb/BlockHeader.hs, src/Chainweb/Version.hs, test/Chainweb/Test/BlockHeader/Validation.hs
Remove legacy logic from devnet. The changes only affect devnet.
=> Devnet updates

.github/workflows/applications.yml, .github/workflows/stack-ci.yaml
Merged this accidentally into the wrong base branch. So I have to recreate this PR.
=> don't run stack ci twice

src/Chainweb/Pact/RestAPI/Server.hs, src/Chainweb/RestAPI.hs, src/Chainweb/Rosetta/RestAPI.hs, src/Chainweb/Rosetta/RestAPI/Server.hs
I will be adding more robust `NetworkId` checking in the next PR.
=> Rosetta Constructions Endpoints

src/Chainweb/Rosetta/RestAPI.hs, src/Chainweb/Rosetta/RestAPI/Server.hs
This also make the `RosettaFailure` type a pure Sum type, so that it's associated Int/Message pairs can be easily extracted.
=> Robust Network Validation

src/Chainweb/Pact/Backend/RelationalCheckpointer.hs, src/Chainweb/Pact/Service/Types.hs, test/Chainweb/Test/Pact/PactInProcApi.hs
=> Use Map instead of list for block transaction history

chainweb.cabal, node/ChainwebNode.hs, node/Utils/InstallSignalHandlers.hs, src/Chainweb/WebPactExecutionService.hs
This resolves a long standing task from our backlog.
The PR improves robustness of the chainweb nodes across restarts. In particular it will guarantee a more graceful shutdown of the databases in situations when a node isn't killed with SIGINT (Ctrl-C).
=> Install signal handlers for SIGTERM

chainweb.cabal, dep/kpkgs/github.json, src/Chainweb/Graph.hs, src/Chainweb/Version.hs, stack.yaml, tools/cwtool/CwTool.hs, tools/known-graphs/KnownGraphs.hs
This also raises the lower bound of digraph, which fixes the twentyChainGraph.
=> Cleanup Chainweb.Graph and provide known-graphs tool

.github/workflows/applications.yml, .github/workflows/stack-ci.yaml
Auto-generated via https://github.com/fosskers/active
=> Github CI Actions Update

src/Chainweb/Pact/PactService.hs, test/Chainweb/Test/Pact/RemotePactTest.hs
Also improves retry timing in test to make execution faster. 
Only change to production code concerns logging.
=> Retry local in RemotePactTest to ensure adequate block height

src/Chainweb/Pact/Backend/ChainwebPactDb.hs, src/Chainweb/Pact/Backend/RelationalCheckpointer.hs, src/Chainweb/Pact/PactService.hs
Use strict `modify'` instead of `.=` and `%=` which are lazy.
=> stricter pact service

src/Chainweb/Pact/Backend/ChainwebPactDb.hs
This PR only changes documentation and failure messages. It doesn't change any production logic.
=> improve documentation and failure messages of handlePossibleRewind

src/Chainweb/Pact/PactService.hs
=> fix pact-service serivce loop

src/Chainweb/Miner/RestAPI/Server.hs
Currently, when a miner submits invalid solved worked, the request fails with status `500 (Internal Server Error) Something went wrong`.
This PR fixes this so that `400 (Invalid Request) Invalid solved work` is returned.
=> Improve failure response for invalid solved work

CHANGELOG.md, chainweb.cabal, node/ChainwebNode.hs, test/Chainweb/Test/Rosetta/RestAPI.hs
=> Version 2.1

src/Chainweb/Pact/PactService/Checkpointer.hs
From time to time some newly started nodes got stuck with
```
Received exception running pact service (syncToBlockBlock): Code invariant violation: withCheckpointerRewind called by rewindTo outside of batch. Please report this as a bug.
CallStack (from HasCallStack):
error, called at src/Chainweb/Pact/PactService/Checkpointer.hs:197:9 in chainweb-2.3-inplace:Chainweb.Pact.PactService.Checkpointer
```
This is a regression from #1168. The change in #1168 splits up a single huge pact-db batch of unbounded size into chunks of small, constant sized, transactions. In order to do so it moves the `withBatch` bracket into the inner rewind loop. However, the implementation missed to add `withBatch` for the corner case of a noop rewind, which by-passes the loop.
=> wrap noop checkpointer use in withBatch

.github/workflows/applications.yml
cf. https://github.com/actions/cache/issues/403
=> [CI] work around cache issue on macOS

src/Chainweb/Pact/SPV.hs, test/Chainweb/Test/Pact/SPV.hs
Currently, `(verify-spv "TXOUT" (read-msg 'proof))` expects the data to be the full JSON of `TransactionOutputProof`. However this is not what the `pact/spv` endpoint returns -- it returns this JSON encoded in base64url-unpadded. 
This changes the "new" TXOUT (post-fork) to expect an object `{ "proof": [base64url-unpadded text] }`. See `createVerify` in the SPV test for the structure.
=> Improve TXOUT proof format

CHANGELOG.md, chainweb.cabal, node/ChainwebNode.hs
=> version to 2.6

CHANGELOG.md, chainweb.cabal, node/ChainwebNode.hs
=> Version 2.7

.github/workflows/applications.yml, .github/workflows/scratch-image.yaml
=> update ci build

chainweb.cabal, src/Chainweb/Chainweb/MinerResources.hs, src/Chainweb/Miner/Coordinator.hs
This gets rid of the dependencies on
* generic-lens,
* generic-lens-core, and
* generic-optics
=> Get rid of generic-lens dependency

Setup.hs
Makes Setup.hs compatible with recent versions of Cabal.
=> modernize Setup.hs

src/Chainweb/Time.hs, test/Chainweb/Test/Roundtrips.hs
This change is factored out from #1244 where it got already approved.
=> fix timeSpanToMicros and add tests

src/Chainweb/Payload/RestAPI/Server.hs
=> Increase batch size of payloads to 1000

src/Chainweb/BlockHeader/Validation.hs
use env. variable to disable mining for devnet
=> Add option to disable mining for devnet

src/Chainweb/Version.hs, test/Chainweb/Test/Pact/PactInProcApi.hs
Tests passing, not needed for 2.11 release.
=> Add tests for enforce-keysets

src/Chainweb/Chainweb.hs, src/Chainweb/CutDB/RestAPI/Server.hs, src/Chainweb/RestAPI.hs
=> include cut, header, and payload endpoints into service api

cabal.project, chainweb.cabal, dep/chainweb-storage/github.json, node/ChainwebNode.hs, node/Utils/InstallSignalHandlers.hs, src/Chainweb/Payload/PayloadStore/RocksDB.hs
Requires upstream PR https://github.com/kadena-io/chainweb-storage/pull/10. Makes checkpoints in `$DBDIR/0/rocksDbCheckpoints`.
=> RocksDB checkpoints with SIGUSR1, now SIGUSR2 does not terminate the node

src/Numeric/Cast.hs
Reopened because I accidentally used my own fork so CI wouldn't run.
=> NumCast instance only if platform allows

.github/workflows/applications.yml, cabal.project, chainweb.cabal
support GHC-9.0 without editing cabal.project
=> update cabal.project file for ghc-9

default.nix, dep/chainweb-storage/github.json, src/Chainweb/Pact/Backend/Utils.hs
=> Bump chainweb-storage nix pin

default.nix
=> fix nix build of resource-pool

src/Chainweb/CutDB.hs
:face_exhaling: had the same issue with pruning before.
=> Start writing cuts at an appropriate frequency

chainweb.cabal, src/P2P/Node.hs, test/ChainwebTests.hs, test/P2P/Test/Node.hs, test/P2P/Test/Orphans.hs
=> Ensure that p2p topology is sufficiently dynamic and random

CHANGELOG.md, chainweb.cabal, node/ChainwebNode.hs, src/Chainweb/Version.hs
=> Version 2.16

.github/workflows/applications.yml, cabal.project, src/Chainweb/CutDB/RestAPI/Server.hs, test/Chainweb/Test/CutDB.hs
Fix the catchup issue we've been seeing on nodes that are significantly behind.
=> Fix cut get endpoint height limiting

README.md
=> Document requirement for cabal >= 3.4

.github/workflows/nix.yml
Need to have exist in master branch to test in different branch
=> nix.yml skeleton

src/Chainweb/Pact/PactService.hs
I have tested this with compaction and it works.
---
- https://app.asana.com/0/0/1205000545311645
=> initializeCoinContract: better heuristic for detecting genesis

bench/Chainweb/Pact/Backend/Bench.hs, src/Chainweb/Pact/Backend/ChainwebPactDb.hs, src/Chainweb/Pact/Backend/RelationalCheckpointer.hs, src/Chainweb/Pact/Backend/Types.hs, src/Chainweb/Pact/Backend/Utils.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/PactService/Checkpointer.hs, src/Chainweb/Pact/PactService/ExecBlock.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Pact/Types.hs, src/Chainweb/Pact/Validations.hs, test/Chainweb/Test/Pact/Checkpointer.hs, test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/PactMultiChainTest.hs, test/Chainweb/Test/Pact/SPV.hs, test/Chainweb/Test/Pact/TransactionTests.hs, test/Chainweb/Test/Pact/Utils.hs, tools/cwtool/TxSimulator.hs
---
- https://app.asana.com/0/0/1205000545311650
=> make PactService use chainweb logging

src/Chainweb/Pact/PactService.hs
---
- https://app.asana.com/0/0/1205043156117013
=> Add requestKeys logging to execNewBlock

chainweb.cabal, src/Chainweb/Pact/PactService.hs, test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/Utils.hs
---
- https://app.asana.com/0/0/1205075354172799
=> Generate UUID for each PactService request

src/Chainweb/Chainweb.hs, src/Chainweb/Chainweb/Configuration.hs, src/Chainweb/Mempool/Mempool.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Service/Types.hs, src/Chainweb/Pact/Types.hs, test/Chainweb/Test/Pact/PactSingleChainTest.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/Utils.hs, tools/cwtool/TxSimulator.hs
---
- https://app.asana.com/0/0/1205043156117005
=> Add timeout to `PreInsertCheck` transaction validation

src/Chainweb/Chainweb.hs, src/Chainweb/Pact/Backend/Compaction.hs, src/Chainweb/Pact/Backend/RelationalCheckpointer.hs, src/Chainweb/Pact/Backend/Types.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Service/Types.hs, src/Chainweb/Pact/Types.hs, src/Chainweb/Rosetta/Internal.hs, test/Chainweb/Test/Pact/PactReplay.hs, test/Chainweb/Test/Pact/PactSingleChainTest.hs, test/Chainweb/Test/Pact/TTL.hs, test/Chainweb/Test/Pact/Utils.hs
Note that this targets the `compaction` branch, not `master`.
=> make PactService exit if rosetta is enabled and we don't have the full history

CHANGELOG.md, node/ChainwebNode.hs, src/Chainweb/Version/Mainnet.hs, src/Chainweb/Version/Testnet.hs
Next service date is Wednesday, December 13th.
=> Cut 2.21 release

.envrc.recommended, .envrc.sample
Summary: Uses the `.envrc` skeleton I use in my projects (which I got from `jj`, myself.) This uses the nix-community `nix-direnv` integration which has some improvements over the default `direnv` implementation. It also tweaks the recommended use of this file by suggesting use of `source` for users, so they can just get all upstream changes easily.
Change-Id: I3e02972580f76e2c1833080315aa99c6
=> chore: .envrc tweaks

src/Chainweb/Pact/PactService.hs
---
- https://app.asana.com/0/0/1205752160865151
=> Halt block fill constructively on refill fetch limit exceeded

bench/Chainweb/Pact/Backend/ForkingBench.hs
PR Goals
- Get rid of unused code paths/code bloat (the 'CoinContractRequest' type was pretty much unused
- Actually submit the amount of TXs the benchmarks claim they do (mempool setting was just broken before)
=> fix block benchmarks

bench/Chainweb/Pact/Backend/ForkingBench.hs, cabal.project, chainweb.cabal, src/Chainweb/Pact/Backend/Compaction.hs, src/Chainweb/Pact/Backend/PactState.hs, test/Chainweb/Test/MultiNode.hs, test/Chainweb/Test/Pact/Compaction.hs, test/Chainweb/Test/Pact/PactSingleChainTest.hs, tools/cwtool/CwTool.hs
compares pact state pre- and post-compaction
---
- https://app.asana.com/0/0/1205378300255963
=> compaction compare pact state tool

CHANGELOG.md, cabal.project, cabal.project.freeze
Also regenerates cabal.project.freeze
=> update to pact410

src/Chainweb/Pact/Backend/RelationalCheckpointer.hs, src/Chainweb/Pact/RestAPI/Server.hs
Just some follow ups from #1775 that I forgot in my tree. These should have no functional change, just improve the errors and readability a bit.
=> poll endpoint: internal cleanups

src/Chainweb/CutDB.hs, test/Chainweb/Test/CutDB.hs
---
- https://app.asana.com/0/0/1206164297538869
=> write cuts more often

c/shathree.c, chainweb.cabal
Add support building `c/shathree.c` as dynamically loadable SQLite3 extension.
=> support dynamic loading of sqlite3 sha3 extension

bench/Chainweb/Pact/Backend/ForkingBench.hs, cabal.project, chainweb.cabal, src/Chainweb/Pact/Backend/Compaction.hs, test/Chainweb/Test/MultiNode.hs, test/Chainweb/Test/Pact/PactSingleChainTest.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/Utils.hs
this code is orthogonal to compaction.
the code is being moved elsewhere.
This PR also includes more detailed logging about how long queries are taking.
---
- https://app.asana.com/0/0/1206176093727369
=> compaction: rip out grandhashing

bench/Chainweb/Pact/Backend/ForkingBench.hs, src/Chainweb/Pact/Backend/Compaction.hs, src/Chainweb/Pact/Backend/PactState.hs, test/Chainweb/Test/MultiNode.hs, test/Chainweb/Test/Pact/PactSingleChainTest.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/Utils.hs
---
- https://app.asana.com/0/0/1204890679652600
=> unify compaction's LogLevel type with the rest of chainweb-node

src/Chainweb/Pact/Backend/RelationalCheckpointer.hs, src/Chainweb/Pact/RestAPI/Server.hs
Resubmitting now that the codefreeze is over.
=> poll endpoint: refactorings

chainweb.cabal, src/Chainweb/Pact/Backend/Compaction.hs, test/Chainweb/Test/MultiNode.hs, test/SlowTests.hs
Add a test that you can compact a live node, and it still makes progress.
---
- https://app.asana.com/0/0/1204890679652603
=> compact live node test

.github/workflows/applications.yml, bench/Bench.hs, chainweb.cabal, src/Chainweb/BlockHeader/Genesis/Development0Payload.hs, src/Chainweb/BlockHeader/Genesis/Development1to19Payload.hs, src/Chainweb/Chainweb/Configuration.hs, src/Chainweb/Pact/Backend/PactState/GrandHash/Calc.hs, src/Chainweb/Version/Development.hs, src/Chainweb/Version/Registry.hs, test/ChainwebTests.hs, tools/cwtool/CwTool.hs, tools/ea/Ea.hs, tools/ea/Ea/Genesis.hs
=> Rename fast-devnet to devnet and change its network ID

src/Chainweb/Pact/Backend/PactState/Diff.hs
We may want to diff each database at a particular height, not just their latest state. Example run to show that this works:
```
❯ $(cabal list-bin cwtool) pact-diff --first-database-dir /home/chessai/sqlite-compacted/sqlite/ --second-database-dir /home/chessai/sqlite/ --target-blockheight 3998134 --log-dir diff-logs
... getting pact state doesn't fail ...
```
=> add a blockheight option to pact-diff

src/Chainweb/Pact/Backend/PactState/GrandHash/Import.hs
- set SNAPSHOT_BLOCKHEIGHT env var. This is so tools such as pact-diff can consume the blockheight.
- print BlockHeight in logs when hashes do or do not align
- expand user-facing help text
- add module-level documentation
- delete commented-out code block
=> pact-import tool: set an environment variable and add more docs.

bench/Chainweb/Pact/Backend/ForkingBench.hs, cabal.project, chainweb.cabal, src/Chainweb/Pact/PactService/ExecBlock.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Rosetta/Utils.hs, src/Chainweb/VerifierPlugin.hs, src/Chainweb/VerifierPlugin/Allow.hs, src/Chainweb/Version.hs, src/Chainweb/Version/Development.hs, src/Chainweb/Version/Mainnet.hs, src/Chainweb/Version/RecapDevelopment.hs, src/Chainweb/Version/Testnet.hs, src/Chainweb/Version/Utils.hs, test/Chainweb/Test/Pact/Checkpointer.hs, test/Chainweb/Test/Pact/PactMultiChainTest.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/TransactionTests.hs, test/Chainweb/Test/Pact/Utils.hs, test/Chainweb/Test/TestVersions.hs
This is an interface for "verifiers", plug-ins into tx verification that are able to grant capabilities and potentially even modify transactions.
This relies on the Pact branch also named edmund/spi. 
---
- https://app.asana.com/0/0/1205797981912170
=> Verifier interface 

src/Chainweb/Pact/Backend/PactState.hs
Change-Id: I1b6d2e1f53b10bd5578fdbee1a6bcd17d5bfd095
=> getLatestPactStateAt: exclude tables created after the particular blockheight

CHANGELOG.md
Not for this release, don't want to delay the release cycle.
=> Update CHANGELOG.md typo

node/ChainwebNode.hs
Change-Id: Ibe04ba2079700025db943832bbe7e46440b92800
=> only respect service date on mainnet and testnet

src/Chainweb/CutDB.hs, src/Chainweb/Pact/RestAPI/Server.hs
Change-Id: If878d9077c0a63425008c5cdfb60b161f4dfc7b0
---
- https://app.asana.com/0/0/1206225958394238
=> listenHandler should wait on blocks and not cuts

bench/Chainweb/Pact/Backend/ForkingBench.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/PactService/Checkpointer.hs, src/Chainweb/Pact/PactService/ExecBlock.hs, src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Pact/Types.hs, tools/cwtool/TxSimulator.hs
Change-Id: I0210312cdf38bef1615a02f3cf0ee57db82894c1
=> disable init module cache on chainweb 224

test/Chainweb/Test/Pact/Utils.hs
https://gerrit.aseipp.dev/q/Ia9840b7cec89e214cf587e48f8887dd94f2e40b8
=> fix(tests): compactUntilAvailable catches CompactExceptionDb

src/Chainweb/Pact/PactService.hs
https://gerrit.aseipp.dev/q/Id5388ad7c747aeddc1badc10eb31b4c41113de7a
=> Stop charging for interface loads

src/Chainweb/Pact/PactService/ExecBlock.hs
https://gerrit.aseipp.dev/q/I71716af37657b5a5881d5b0f4a592d1690baa11f
=> docs: Comment module cache weirdness

src/Chainweb/Pact/Backend/PactState/GrandHash/Calc.hs
Change-Id: Idb469984e612f28c7606b9111b16d9afc4a7f790
=> add an --every option to pact-calc

bench/Chainweb/Pact/Backend/ForkingBench.hs, src/Chainweb/Pact/Backend/Compaction.hs, src/Chainweb/Pact/Backend/PactState.hs, src/Chainweb/Pact/Backend/PactState/Diff.hs, test/Chainweb/Test/Pact/PactSingleChainTest.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Pact/Utils.hs
Change-Id: I7ff377e0a3504b703e46dda6e3cce3b3794e71c3
=> compaction: add LatestSafe and simplify CLI UX

src/Chainweb/Pact/PactService/ExecBlock.hs
Before this change, transactions can time out but still commit part of their
writes to the block state. This isn't a problem currently as far as I know
because that state is always thrown out regardless, but with incremental
NewBlock that changes.
https://gerrit.aseipp.dev/q/Ia58a72fb7766dc5d5714aeea4f6323c8c8fdc32f
=> fix: revert block state after transaction times out

src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/PactService/ExecBlock.hs
https://gerrit.aseipp.dev/q/If9aabf4fe96eb6f88ac665e2d2fcc779e2754d6f
=> fix: propagate modulecache across refills

test/Chainweb/Test/MultiNode.hs
https://gerrit.aseipp.dev/q/I5196ee46d8c0e45bae6ee105049d28852977de45
=> docs: describe replayTest as flaky

src/Chainweb/Pact/Backend/PactState/GrandHash/Calc.hs
Change-Id: I4fe1778ca5e33483d5d65c1c311876829a54eeb0
=> pact-calc should fail if you attempt to write mismatched hashes

src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Templates.hs, src/Chainweb/Pact/TransactionExec.hs, test/Chainweb/Test/Pact/RemotePactTest.hs, test/Chainweb/Test/Rosetta/RestAPI.hs
This change makes buying gas take less database space, less time, and less gas.
This change is forking.
https://gerrit.aseipp.dev/q/Ia1033ed742bc79b2780b90bc45aad2118673405d
=> Buy and redeem gas directly without a defpact

.github/workflows/applications.yml
https://gerrit.aseipp.dev/q/If62923a93085bee3d4236dc4e152a358e7ea1801
=> add cwtool to CI

src/Chainweb/Pact/TransactionExec.hs, src/Chainweb/Utils/Serialization.hs, src/Chainweb/VerifierPlugin.hs, src/Chainweb/VerifierPlugin/Allow.hs, src/Chainweb/VerifierPlugin/Hyperlane/Announcement.hs, src/Chainweb/VerifierPlugin/Hyperlane/Binary.hs, src/Chainweb/VerifierPlugin/Hyperlane/Message.hs, src/Chainweb/VerifierPlugin/Hyperlane/Utils.hs, test/Chainweb/Test/Pact/VerifierPluginTest/Transaction.hs
Implements the MerkleTree ISM verifier plugin.
=> Add Merkle tree ISM verifier plugin

bench/Chainweb/Pact/Backend/ForkingBench.hs, src/Chainweb/Chainweb/MinerResources.hs, src/Chainweb/Cut/Create.hs, src/Chainweb/Cut/CutHashes.hs, src/Chainweb/CutDB.hs, src/Chainweb/Miner/Coordinator.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/PactService/Checkpointer.hs, src/Chainweb/Pact/PactService/ExecBlock.hs, src/Chainweb/Pact/Service/BlockValidation.hs, src/Chainweb/Pact/Service/Types.hs, src/Chainweb/Payload.hs, src/Chainweb/Sync/WebBlockHeaderStore.hs, src/Chainweb/WebPactExecutionService.hs, test/Chainweb/Test/CutDB.hs, test/Chainweb/Test/Orphans/Internal.hs, test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs, test/Chainweb/Test/Pact/PactExec.hs, test/Chainweb/Test/Pact/PactReplay.hs, test/Chainweb/Test/Pact/PactSingleChainTest.hs, test/Chainweb/Test/Pact/TTL.hs, test/Chainweb/Test/Pact/Utils.hs, tools/cwtool/TxSimulator.hs
https://gerrit.aseipp.dev/q/I076bd8411544f039f9869193dbffc5a623808645
=> feature: include outputs in validation errors from locally mined blocks

test/Chainweb/Test/Utils.hs
Makes the tests that wait for a cut height stop logging
that they're doing so. This should substantially decrease
the amount of terminal output in these tests, and I've never
used these log messages.
https://gerrit.aseipp.dev/q/If6c27d695aae55b0a9cff0bd390d9467b431ba64
=> fix: make tests quiet down

src/Chainweb/Pact/PactService.hs
Stops refill (i.e. newblock, at this point) once we have a timeout.
This restores older behavior and makes newblock more resilient.
Test plan: just our existing tests.
https://gerrit.aseipp.dev/q/Ide28e16f8bfb67fc309f3e81d1698dc8c13561bd
=> fix: stop refill on timeout

test/Chainweb/Test/Pact/PactMultiChainTest.hs
Now it checks that we've actually made a block, and that newblock stopped
filling the block after the timeout.
https://gerrit.aseipp.dev/q/I8fe057cabe09b65a4e3833a7cce7e36e51480862
=> test: tx timeout test includes more behavior

src/Chainweb/Version/Development.hs, src/Chainweb/Version/RecapDevelopment.hs
This is just to make it easier to test veriifers with
client programs like chainweb-data
https://gerrit.aseipp.dev/q/Ia4148400f64765f7dc468122e8c8820c69260c4d
=> feature: add "allow" verifier to devnet

src/Chainweb/Pact/PactService.hs
https://gerrit.aseipp.dev/q/I3d302f78a77cdb679a97b4fa8f570c3d9a47011d
=> logs: remove Sum from the log for played fork blocks

test/Chainweb/Test/Pact/PactSingleChainTest.hs
Timeouts are tricky to trigger in GH actions. We're satisfied if it's triggered once in 100 runs. 
https://gerrit.aseipp.dev/q/I72c6f717ef13eb4ff28ed9b0e9fbbed4b782579f
=> tests: run preInsertCheckTimeoutTest 100 times

src/Chainweb/BlockHeader.hs, src/Chainweb/Cut.hs, src/Chainweb/Cut/Create.hs, src/Chainweb/Graph.hs
Few typo fixes and more verbose errors related to flaky tests 
https://gerrit.aseipp.dev/q/If269219907e093d642ee2f9929c1c5cd79101444
=> Few typo fixes and more verbose errors related to flaky tests

src/P2P/Node/Configuration.hs
Change-Id: I1e2e1cc4ddd96c01d8d7ec5d38935ef10eb62fb3
=> Log describing a totally private node config more accurately

changes/2024-05-30T133934-0500.txt, make_change_file
Change-Id: Ic9e078d57cdec4c8a5b56e50feb1688bd151b707
=> add changes folder and a script to help devs

changes/2024-05-30T145855-0400.txt, src/Chainweb/BlockHeader/Validation.hs
Lead with description, follow with header, add parent and adjacents  only if relevant and available.
Change-Id: Iba0c7994480e9e958b61529c7d521241a5867bd9
=> log: reorganize Show ValidationFailure error message

changes/2024-05-30T150129-0400.txt, node/ChainwebNode.hs
Change-Id: I89f8b6dfd1ac32502e27ca4c13bb40b309248f14
=> log: add a telemetry backend for P2P stats

changes/2024-05-30T143733-0500.txt, src/Chainweb/Pact/PactService.hs
Change-Id: I98a97488cbdf85a25a3e2b8effb52bf34012dc5d
=> restore execNewBlock timeout logging

changes/2024-05-30T145702-0400.txt, node/ChainwebNode.hs, src/Chainweb/Chainweb.hs, src/Chainweb/Chainweb/CutResources.hs, src/Chainweb/CutDB.hs, src/Chainweb/Mempool/InMem.hs, src/Chainweb/Pact/Backend/ChainwebPactDb.hs, src/Chainweb/Pact/Backend/Utils.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/PactService/Checkpointer.hs, src/Chainweb/Pact/Service/PactInProcApi.hs, src/Chainweb/Utils.hs, src/P2P/Node.hs
Change-Id: I4cb783bd70b14f5175bbb21b29cbda6501e3bf7c
=> log: less verbose during initialization

changes/2024-05-30T145831-0400.txt, src/Chainweb/Chainweb.hs
These errors are not concerning individually unless we're  debugging an existing issue.
Change-Id: I09b16e5db5ddf1472de685ecf450b72e685b9fd3
=> log: warp server errors at Debug level

.github/workflows/misc.yaml
This will hard block us if we forget these in the future.
Change-Id: I04c48eada81378add1ac7f2171f7c6430d549427
=> github: do not allow FIXMEs in the changelog

test/Chainweb/Test/MultiNode.hs
Change-Id: I16340f61cb7cdea49580735eb421c007d4a6143f
=> test: increase cut fetch timeout in slow tests

cabal.project, changes/2024-06-14T103642-0500.txt
Change-Id: I1b6c2eeff1b77f12b6f61a6b873b9cf512c32bf7
=> update pact pin

src/Chainweb/Mempool/InMem.hs
Change-Id: Ie3fa2e14f4fd5b36a73dd09c2a75c277882d9d57
=> move getBlockInMem log to debug

src/Chainweb/CutDB.hs
The trace telemetry would never happen if we timed out, making it very unclear which cuts timed out while being fetched.
Change-Id: I2a4a92d6a600b8cd47ad61d2403397bc72a7bfeb
=> log: put cut fetch trace telemetry around timeout instead of inside

changes/2024-05-30T141646-0500.txt, src/Chainweb/CutDB.hs
Change-Id: I82e10ee63220a2d1524c973992dc4e47e0a45f30
=> don't prune cuts at startup

changes/2024-05-30T141430-0500.txt, src/Chainweb/CutDB.hs
Change-Id: Idc27197e527dbc88089acddc812c0d3812c6eaf9
=> correct cut pruning math: max -> min

changes/2024-05-30T145526-0500.txt, src/Chainweb/Pact/PactService.hs
Change-Id: I176b803aa6399e0df8c39d5d6d9eecbce238dcb5
=> silence default exception handler in pactqueue forked thread

.github/workflows/release.yml
Change-Id: I0c5e2cc6fd519affc2444cbcc41ab4f0dd133ea0
=> Add compact executable to ubuntu binary release

README.md
**"inquires"**
Error: Incorrect word usage.
Correction: "inquiries"
**"IMPORTANT NODE"**
Error: Typo.
Correction: "IMPORTANT NOTE"
**Corrected.**
=> Typos Update README.md

node/src/ChainwebNode.hs
Change-Id: Id45bc33f9fbdc799126df13c091961b03b5b1024
=> correct node shutdown message due to old ChainwebVersion

src/P2P/Node.hs
Change-Id: Ieca25025c414918bf1e7b2b2306b0764b0110a0e
---
- https://app.asana.com/0/0/1208669373066724
=> increment p2p successive failure count of failed peer syncs

src/Chainweb/Chainweb.hs, src/Chainweb/Chainweb/CheckReachability.hs
---
- https://app.asana.com/0/0/1208751106070235
=> Add Server header

src/Chainweb/Chainweb/Configuration.hs
Change-Id: I489588553d70721550928542fbd61908f8c46c28
=> add missing pact5Devnet in isDevelopment check

src/Chainweb/Version/Registry.hs
Change-Id: Ife724b6b4a3d18e840f98dc5adc141b206d48209
=> better error message on devnet mismatch

src/Chainweb/Pact5/SPV.hs
Change-Id: If906d8d82610e266a8879dd92d7a9440a102e54a
=> add catchAndDisplaySPVError to pact5 SPV

bench/Chainweb/Pact/Backend/ForkingBench.hs, src/Chainweb/Chainweb.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/Types.hs, test/lib/Chainweb/Test/Pact4/Utils.hs, test/lib/Chainweb/Test/Pact4/VerifierPluginTest/Transaction.hs, test/lib/Chainweb/Test/Pact4/VerifierPluginTest/Transaction/Message/After225.hs, test/lib/Chainweb/Test/Pact4/VerifierPluginTest/Transaction/Message/Before225.hs, test/unit/Chainweb/Test/Pact4/PactMultiChainTest.hs, test/unit/Chainweb/Test/Pact4/PactSingleChainTest.hs
This name more obviously reflects what it does.
=> Rename _pactBlockGasLimit to _pactNewBlockGasLimit

src/Chainweb/Pact/PactService/Pact4/ExecBlock.hs, src/Chainweb/Pact/PactService/Pact5/ExecBlock.hs
Unfortunately the old one just keeps failing us for various reasons and is not super obvious. What would be super obvious would be a message like "header, actual payload, expected payload (if available)", and that's what this is.
=> More straightforward BlockValidationFailure message

cabal.project, src/Chainweb/Pact5/TransactionExec.hs, test/unit/Chainweb/Test/Pact5/CutFixture.hs, test/unit/Chainweb/Test/Pact5/RemotePactTest.hs, test/unit/Chainweb/Test/Pact5/TransactionExecTest.hs
Please review commit-by-commit. Each commit has a description like a PR description, but better, because it's in the git history.
=> Testing package

src/Chainweb/Pact/Types.hs, src/Chainweb/Version.hs, test/lib/Chainweb/Test/TestVersions.hs, test/unit/Chainweb/Test/Pact5/RemotePactTest.hs
Change-Id: If184ef67386c53a77b4aee1fe3c74198efa78452
=> add a test that spv works across the Pact4->Pact5 transition

test/unit/Chainweb/Test/Pact5/TransactionTests.hs
Change-Id: I073a658c91f39cb34a6ff3369c5ed701655e916d
=> port pact4 miner key injection test to pact5

bench/Bench.hs, bench/Chainweb/MempoolBench.hs, chainweb.cabal
Change-Id: Id0000000f877bff9ab7888eed3c229decd1bbb61
=> Add Mempool benchmarks

test/unit/Chainweb/Test/Pact5/RemotePactTest.hs
Just a couple of the tests (the first two) from ns-upgrade.test.js in the integration tests.
Change-Id: Id0000000241e475fa446902a413ff24ddbc5254a
=> namespace contract upgrade tests

bench/Chainweb/MempoolBench.hs
Inserting multiple batches tests the performance of the mempool once we've already got some txs in the pending list, and having some overlap in those batches tests how it behaves in a more practical situation, when many of the transactions it receives are already pending locally.
=> Extra mempool benchmarks

src/Chainweb/Pact/PactService.hs
This should make larger batches cheaper to pre-insert check, because they won't have to reload the coin module.
Change-Id: Id0000000558b7a0eb9399b6d94a59a03fa14ea43
=> Persist pending writes/reads across txs in pre-insert check batch 

cabal.project
Change-Id: Id0000000cde57e16ff5763cb9e734dd08a3629e9
=> Update ixset-typed dependency to fix master

src/Chainweb/Version/Registry.hs
Change-Id: Id000000011569e25d5033fa63de63fec483b8cc2
=> Remove from and reorder knownVersions

src/Chainweb/Chainweb.hs, src/Chainweb/Chainweb/Configuration.hs
Change-Id: Id000000014dc8554cba51f00aec7711cd8856335
=> Move header stream config into its own area

src/Chainweb/Chainweb/Configuration.hs
Change-Id: Id00000002aa16bd774416bfd6d9b44ae1526eec6
=> Add examples to version option

src/Chainweb/PayloadProvider/EVM.hs
Change-Id: Id0000000a95d821cbb42fa0640dcd4bfbeb83d3a
=> Improved error messaging around EVM PP init

src/Chainweb/Chainweb/Configuration.hs
Change-Id: Id00000001d225a8fefe8038c380cd3b06b02f734
=> Put minimal PP options into a group

src/Chainweb/PayloadProvider/Pact/Configuration.hs
There is no more pact queue
Change-Id: Id0000000cf6e3c746b03f249901af373d9e013dd
=> Delete pact queue size option

src/Chainweb/Cut/Create.hs
Change-Id: Id0000000fece787f99054a6213fdf54c5075135c
=> Fix limitCut performance regression

src/Chainweb/Pact/Backend/Compaction.hs, src/Chainweb/SPV.hs, src/Chainweb/Version.hs, src/Chainweb/Version/Development.hs, src/Chainweb/Version/Guards.hs, src/Chainweb/Version/Mainnet.hs, src/Chainweb/Version/RecapDevelopment.hs, src/Chainweb/Version/Testnet04.hs, test/lib/Chainweb/Test/TestVersions.hs
also sorted imports with ImportQualifiedPost
=> add minimal block header history constant

src/Chainweb/TreeDB.hs
Change-Id: Id00000007a01544a082202e1f6f756658ae72b31
=> Change some names in getBranch

src/Chainweb/CutDB.hs, src/Chainweb/Sync/WebBlockHeaderStore.hs
Fixes fork resolution during the initialization of payload providers.
=> fix fork resolution in initial payload provider sync

src/Chainweb/Pact/Backend/ChainwebPactDb.hs, src/Chainweb/Pact/Backend/Utils.hs, src/Chainweb/Pact/PactService.hs, src/Chainweb/Pact/PactService/Checkpointer.hs, src/Chainweb/PayloadProvider/Pact/BlockHistoryMigration.hs
It seems that since adding the read-only connection pool we get misuse errors from sqlite occasionally when releasing savepoints. I can't tell how exactly savepoints are implemented, and there is no sqlite documentation on the interaction between multiple readers and savepoints for read transactions and the WAL file all together, *but*, the simple policy that transactions are only begun from PactService.hs seems sufficient to give us the same guarantees as we got from savepoints anyway.
Change-Id: Id000000058775f60cd5949497a34d0fb06584190
=> Delete sql savepoints from Pact PP, use sql transactions
