src/P2P/Peer.hs

These DNS names are unused, so I remove them here to avoid confusion.
This also means we no longer need to have our running nodes ignore these non-existent bootstraps. <- @mightybyte

Remove obsolete bootstrap nodes

---

tools/ea/Ea.hs

*Therefore Ilúvatar gave to their vision Being, and set it amid the Void, and the Secret Fire was sent to burn at the heart of the World; and it was called Eä.* :fire:

Improve the  Eä quote

---

src/Chainweb/CutDB.hs
src/Chainweb/Miner/POW.hs

The performance of the inner mining loop is roughly doubled be checking whether the pow hash meets the target directly on the buffers without first converting to `PowHashNat`.

speed up mining with faster target check

---

src/Chainweb/BlockHeader/Genesis.hs
src/Chainweb/Chainweb/MinerResources.hs
src/Chainweb/CutDB.hs
src/Chainweb/Difficulty.hs
src/Chainweb/Graph.hs
src/Chainweb/Miner/POW.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/PowHash.hs
src/Chainweb/RestAPI/Orphans.hs
src/Chainweb/Version.hs
src/P2P/Peer.hs
test/Chainweb/Test/Orphans/Internal.hs
test/Chainweb/Test/P2P/Peer/BootstrapConfig.hs

This PR allows the usage of `ChainwebVersion` text representations like `testWithTime-peterson` instead of `testWithTime-4075880449`. This applies to CLI flags, as well as JSON.
In turn, this fixes the "version `Map` priming" problem, which blocks further work elsewhere (#135).
The new accepted postfixes are:
- `-singleton`
- `-pair`
- `-triangle`
- `-peterson`
- `-twenty`
- `-hoffman-singleton`

Statically-known Text representations for `ChainwebVersion`

---

src/Chainweb/Difficulty.hs
src/Chainweb/TreeDB/Difficulty.hs

From the Haddocks:
> Spikes in *HashRate* may occur as the mining network grows and shrinks. To ensure that adjustment does not occur too quickly or with too much granularity, we enforce a "minimum factor of change" (Z) for `adjust`. If `adjust` notices that the change for the given window is not large enough, then it will not occur. The overall pattern of difficulty then becomes less of a rippling pond, and more of a series of plateaus with distinct jumps. Analysis has been shown that Z should be greater than a factor of e=2.71828⋯ (source needed).
In particular, this change softens the effect of sudden addition / loss of mining power. For our current production `ChainwebVersion`s we set the minimum required change to be `3`. Therefore, on average (when we're already half way through a …

Minimum Difficulty Adjustment Thresholds

---

default.nix

See this link for how this change looks in CI when there is a test failure:
https://gitlab.com/kadena-io/chainweb-node/-/jobs/208064271

Pass --hide-successes to test suite

---

chainweb.cabal
stack.yaml
tools/txg/TXG.hs
tools/txg/TXG/Types.hs

This PR allows one to send transactions in batches, the size of which can be defined on the command line.

TXG: Transaction Batches

---

chainweb.cabal
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Crypto/MerkleLog.hs
src/Chainweb/Difficulty.hs
src/Chainweb/Mempool/Mempool.hs
src/Chainweb/Miner/Test.hs
src/Chainweb/Time.hs
test/Chainweb/Test/MultiNode.hs

This PR adds `-Widentities` to our warnings, and fixes the issues it highlights.
From the GHC User's Guide:
> Causes the compiler to emit a warning when a Prelude numeric conversion converts a type T to the same type T; such calls are probably no-ops and can be omitted. The functions checked for are: toInteger, toRational, fromIntegral, and realToFrac.

-Widentities

---

chainweb.cabal
tools/txg/TXG.hs
tools/txg/TXG/Types.hs

In the spirit of #223 , this PR adds two more warning flags. 
From the GHC User Guide:
> The option `-Wpartial-fields` warns about record fields that could fail when accessed via a lacking constructor. 
> `-Wcompat` turns on warnings that will be enabled by default in the future, but remain off in normal compilations for the time being. This allows library authors eager to make their code future compatible to adapt to new features before they even generate warnings.

-Wcompat and -Wpartial-fields

---

stack.yaml

A reformatting of our `stack.yaml` to match Pact and to be explicit where each pinned dependency is coming from. This will make it easier to keep organized in the future.
The resolver is not updated - that's left for #215 .

Stack Hygiene 

---

src/Chainweb/Chainweb.hs
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Mempool/InMemTypes.hs
src/Chainweb/Mempool/Mempool.hs
src/Chainweb/Mempool/RestAPI.hs
src/Chainweb/Mempool/RestAPI/Client.hs
src/Chainweb/Mempool/RestAPI/Server.hs
test/Chainweb/Test/Mempool.hs
test/Chainweb/Test/Mempool/InMem.hs
test/Chainweb/Test/Mempool/RestAPI.hs
test/Chainweb/Test/Mempool/Sync.hs

- remove old subscription semantics, replace with a "recent inserts" log
- change REST getPending API to optionally tail the recent inserts log starting from a "high water mark"
- update current polling sync algorithm to do initial bi-directional sync, then perform subsequent sync using high water mark. Pull-only for now.

Rework mempool sync logic.

---

tools/txg/TXG.hs

The comment in the code blow seems to indicate that the sender id should always by "sender00".
```Haskell
testSomeKeyPairs :: IO [SomeKeyPair]
testSomeKeyPairs = do
let (pub, priv, addr, scheme) = someED25519Pair
apiKP = ApiKeyPair priv (Just pub) (Just addr) (Just scheme)
mkKeyPairs [apiKP]
-- | note this is "sender00"'s key
someED25519Pair :: (PublicKeyBS, PrivateKeyBS, Text, PPKScheme)
someED25519Pair =
( PubBS $ getByteString
"368820f80c324bbc7c2b0610688a7da43e39f91d118732671cd9c7500ff43cca"
, PrivBS $ getByteString
"251a920c403ae8c8f65f59142316af3c82b631fba46ddea92ee8c95035bd2898"
, "368820f80c324bbc7c2b0610688a7da43e39f91d118732671cd9c7500ff43cca"
, ED25519
)
```

[TXG] fix sender id

---

tools/txg/TXG.hs
tools/txg/TXG/Simulate/Contracts/Common.hs
tools/txg/TXG/Types.hs

This PR allows one to send a single TX and immediately wait for the result (via an internal `listen/` call).
Sample output, having sent `(+ 1 2)`:
```
ListenResponse 
( CommandResult 
{ _crReqKey = "O4pvMdZB9IzsvjrD4PfCsqZhOxa50ha98EFuONABvyo"
, _crTxId = Just 120
, _crResult = PactResult ( Right ( PLiteral ( LDecimal { _lDecimal = 3 } ) ) )
, _crGas = Gas 1
, _crLogs = Just "1sG131AkRe4pR0oMjpcvhYIfMP_VhYk5wTZ6sVoxhNI"
, _crContinuation = Nothing
, _crMetaData = Nothing
} 
)
```

TXG: Single Transactions

---

cabal.project
src/Chainweb/BlockHeaderDB.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Mempool/RestAPI/Client.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/TreeDB.hs
src/Chainweb/Utils.hs

This PR improves performance of Chainweb-node startup:
The PR also contains a few small fixe along the way:

Performance improvements for chainweb-node startup

---

cabal.project
default.nix
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/SPV.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
stack.yaml
test/Chainweb/Test/Pact/Checkpointer.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/SPV.hs
test/Chainweb/Test/Pact/Utils.hs
tools/ea/Ea.hs
tools/txg/TXG.hs
tools/txg/TXG/Simulate/Contracts/Common.hs

General housekeeping: 
- Pact's `ChainId` type has been moved to its own module
- `SPVSupport` now features a second function supporting SPV-based cross-chain defpact validation which needs to be filled in 
- You may now find all continuation data for defpacts (`PactExec`, `PactStep` etc.) in `Pact.Types.Continuation`. 
- You may now find all SPV-related Pact types in `Pact.Types.SPV`
- The type of `evalContinuation` has changed - it no longer takes a `Maybe PactExec`, taking a `ContMsg` instead.

Bump Pact Version to Include SPV-based defpacts

---

.gitlab-ci.yml
Setup.hs
chainweb.cabal
src/Chainweb/Chainweb/ChainResources.hs
tools/txg/TXG.hs

Injecting this file into the build means that the nix-hash depends on the git revision (and branch and tag names). This is acceptable, because, indirectly it already depended on the revision, by pulling the sources based on the revision. The assumption is that already it is very rare for chainweb that two different git revisions result in the same nix hash.

gitlab git info

---

src/Chainweb/BlockHeaderDB.hs
src/Chainweb/Chainweb/ChainResources.hs

The existing implementation of pruning could in rare cases result in a block header that was missing its payload. This could happen if all blocks in a prefix of a fork were marked as false positives but the respective payloads were not marked. (False positive blocks with an unmarked predecessor are detected and deleted.)
The PR fixes the issue by detecting and deleting any falsely marked block for which the payload hasn't been marked. This correct, because the payloads for all blocks on the root forks are marked.
This guarantees that for each block header the respective payload exists. It also lowers the false positive rate for block headers even further. 
Note, that we don't require that for each payload there is a respective block header. We therefor don't do any effort to detect …

fix pruning of block header db

---

chainweb.cabal
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Mempool/RestAPI.hs
src/Chainweb/Mempool/RestAPI/Client.hs
src/Chainweb/Mempool/RestAPI/Server.hs

Mempool pending transactions without streaming

---

src/Chainweb/Mempool/Consensus.hs
src/Chainweb/Transaction.hs

1. improve Hashable instance for pact transactions (use existing _cmdHash instead of re-encoding and hashing)
2. fix O(n^2) vector cons loops in Chainweb.Mempool.Consensus
3. strictify some folds

[mempool] some performance fixes.

---

src/Chainweb/BlockHeader.hs
src/Chainweb/Cut/Test.hs
src/Chainweb/Difficulty.hs
src/Chainweb/Mempool/Mempool.hs
src/Chainweb/Miner/POW.hs
src/Chainweb/Time.hs
src/Chainweb/TreeDB/Difficulty.hs
src/P2P/Node.hs
test/Chainweb/Test/CutDB.hs
test/Chainweb/Test/Roundtrips.hs

This PR makes us explicit about our usage of a microsecond unit in our `Time` type. This decreases chaos in Difficulty Adjustment and Hash Power Estimation.
Closes #260

Explicit Microseconds

---

src/Chainweb/Chainweb.hs
src/Chainweb/Cut.hs
src/Chainweb/TreeDB.hs

When getting new cuts nodes requests cuts that are only at most 1000 blocks ahead of the current cut of the node. The reason for that is to make nodes catching up more iteratively by going in chunks of 1000 blocks.
On the server side a limited cut is computed by using `branchEntries` which traverses the block header dbs backward until it reaches blocks at the target height. This traversal is currently not optimized. It follows the parent pointer with point wise lookups instead of using a reverse iterator, which has complexity `O(n)`. This works well for most cases because most of the time the number of traversed blocks is relatively small, and, thus, `n` is constant. For `limitCut` the `n` is in the order of the block height of the chain for each 1000-block chunk, and the overall …

optimize limit cut function

---

.gitlab-ci.yml
default.nix

CON: Doc generation has been disabled for the time being. Otherwise, it works! Deploying nodes is now at least 20x faster.

Static Nix Executables

---

cabal.project
default.nix
src/Chainweb/Chainweb.hs
src/Chainweb/CutDB.hs
stack.yaml

This PR updates the pin for [chainweb-storage](https://github.com/kadena-io/chainweb-storage). The review should include the commits
* https://github.com/kadena-io/chainweb-storage/commit/5d12e51fc97183d9d52e8ceb634e0aab627590dc and
* https://github.com/kadena-io/chainweb-storage/commit/351ace4436b1d88f96e9d17dfeecfcb58f205027.
This PR also fixes a bug, that causes a dead-lock during initialization of a CutDB with a corrupted database. When the stored 'CutHashes' referred to a block header that was missing from the local chained, the CutDB tried to load the missing header from the network by queuing a task for it. But during CutDB initialization, the process for serving the queue and fetching and validating remote headers and payloads hasn't yet started.
This PR fixes the issue by …

Fix a Chainweb-storage bug and make initialization more robust

---

chainweb.cabal
node/ChainwebNode.hs
src/Chainweb/Logging/Amberdata.hs
src/Chainweb/Utils.hs

This PR
The solution is agnostic of the case of failure that just does a best effort for the general case where failure may or may not be permanent. It also assumes that the node shouldn't be killed completely in case of an unknown failure in a monitor and that submitting error logs is sufficient.
Handlers for specific failure modes of monitors should be added in addition and on top of the strategy implement in this PR.

Fix spinning of RTS monitor without `+RTS -T`

---

chainweb.cabal
src/Chainweb/Cut.hs
src/Chainweb/CutDB.hs

The PR provides stream that provide all bocks in a branch of a Chainweb represented by a stream of cuts.
`blockStream` is a prerequisite for the follow up PR for #292 that will ensure that actually all blocks are published to Amberdata and blocks aren't published twice.

implement blockStream and cutStreamToHeaderStream

---

src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Mempool/InMemTypes.hs
test/Chainweb/Test/Mempool/InMem.hs
test/Chainweb/Test/Mempool/RestAPI.hs
test/Chainweb/Test/Mempool/Sync.hs
test/ChainwebTests.hs

This persists the validated transactions into RocksDB.
The main motivation for this PR is to store the validated transactions in encoded form which is more memory efficient than storing the parsed Command along with all its dependencies, and the encoded transaction in memory.
Well, from there it was just a tiny step to use `RocksDbTable` instead of an in memory table/map.

persist validated tx in the Mempool into RocksDB

---

src/Chainweb/Chainweb.hs
src/Chainweb/Pact/Service/PactInProcApi.hs

NOTE: The function `Chainweb.Mempool.InMem.getBlockInMem` takes `InMemConfig t` as parameter, which contains `blockGasLimit` as configured in `Chainweb.Chainweb`. However, it ignores it and instead uses the hard-coded value `Chainweb.Pact.Service.PactInProcApi.maxBlockSize` that is provided as extra argument. That’s confusing. Which value is supposed to be used?

Increase block gas limit to allow blocks of up 1000 tx in devnet

---

src/Chainweb/Pact/BloomCache.hs

Femove lazy pattern match in creation of bloom filters. Instead force bloom filter computation to prevent them from retaining all resources of all transaction that were added to the bloom filters.

force bloom filter calculation in bloom tx cache

---

chainweb.cabal
node/ChainwebNode.hs
src/Chainweb/Logging/Amberdata.hs
src/Chainweb/Logging/Config.hs
src/Utils/Logging/Config.hs

Version 2 of Amberdata logging.
- Improves amberdata config flags.
- Amberdata can now be enabled/disabled via `--enable-amberdata-logger`. Disabled by default.
- Enables config validation
- Adds flag for only sending single chain information. If flag missing or null in the config file, then all chain information will be sent.
```
$stack exec -- chainweb-node --enable-amberdata-logger --amberdata-chain-id 0
```
- Adds payload transactions to blocks logging
- Adds payload size to blocks logging
To test:
```
$ stack exec -- chainweb-node --enable-amberdata-logger --amberdata-host <HOST>:<PORT> --amberdata-api-key <API-KEY> --amberdata-blockchain-id<BLOCKCHAIN-ID> --enable-amberdata-debug
```

Amberdata logging: Adds payload tx and size & allows sending single chain

---

chainweb.cabal
src/Chainweb/Chainweb/MinerResources.hs
src/Chainweb/Miner/Config.hs
src/Chainweb/Miner/Miners.hs
src/Chainweb/Utils.hs
test/Chainweb/Test/Misc.hs
test/ChainwebTests.hs

This PR ensures that brittle/failing connections between `chainweb-node` and `chainweb-miner` processes will not cause problems.

Remote Miner Communication Resiliance 

---

chainweb.cabal
miner/Miner.hs
src/Chainweb/Miner/Coordinator.hs
src/Chainweb/Miner/Core.hs
src/Chainweb/Miner/Miners.hs
test/Chainweb/Test/Miner/Core.hs
test/Chainweb/Test/Pact/PactReplay.hs
test/ChainwebTests.hs

This PR alters the `MiningAPI` type to expect pre-encoded versions of every argument. This way, our Mining Client (or any such 3rd-party client) needs to know *very* little about how our types are constructed. This should make it even easier to write new clients.
As evidence, the `Chainweb.Miner.Core` module (which powers both our in-process POW mining and our remote POW mining) now has but a single Chainweb import: the `Version` module.

Miner takes a Byte out of Life

---

src/Chainweb/BlockHeader/Genesis.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Difficulty.hs
src/Chainweb/Miner/Core.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/PowHash.hs
src/Chainweb/Version.hs
src/P2P/Peer.hs
test/Chainweb/Test/Orphans/Internal.hs
test/Chainweb/Test/P2P/Peer/BootstrapConfig.hs

This chainweb version is for use primarily with the upcoming
standalone executable.

New Chainweb Version - FastTimedCPM

---

chainweb.cabal
src/Chainweb/Pact/Backend/InMemoryCheckpointer.hs
src/Chainweb/Pact/Backend/RelationalCheckpointer.hs
src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/Service/BlockValidation.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/WebPactExecutionService.hs
src/Chainweb/WebPactExecutionService/Types.hs
test/Chainweb/Test/CutDB.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/Utils.hs

Lars and Emily also need the new included internal pact execution service lookup method for SPV.

Make pact /poll endpoint use the pactdb tx index.

---

src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Mempool/InMemTypes.hs
src/Chainweb/Mempool/Mempool.hs
src/Chainweb/Mempool/RestAPI/Client.hs
src/Chainweb/Mempool/RestAPI/Server.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/Service/PactInProcApi.hs
test/Chainweb/Test/Mempool.hs
test/Chainweb/Test/Mempool/InMem.hs
test/Chainweb/Test/Mempool/RestAPI.hs
test/Chainweb/Test/Mempool/Sync.hs
test/Chainweb/Test/Pact/PactReplay.hs
tools/standalone/Standalone/Chainweb.hs

We're re-gossiping old transactions in the mempool -- this change eagerly checks them, at the expense of moving the checkpointer more often.

[mempool] add a pre-insert check.

---

miner/Miner.hs
src/Chainweb/Chainweb/MinerResources.hs

This PR makes `chainweb-miner` follow the precedent for dealing with servant bounds.

Miner: Treat Servant more Rigorously

---

src/Chainweb/Pact/TransactionExec.hs

Possibly unnecessary -- presumably any transaction has blown up already with gas prices of invalid precision. Leaving in DRAFT until we decide

round gas fee

---

src/Chainweb/BlockHeaderDB/RestAPI.hs
src/Chainweb/BlockHeaderDB/RestAPI/Server.hs
src/Chainweb/Chainweb.hs
src/Chainweb/CutDB/RestAPI.hs
src/Chainweb/CutDB/RestAPI/Server.hs
src/Chainweb/RestAPI.hs
test/Chainweb/Test/Mempool/RestAPI.hs
test/Chainweb/Test/Utils.hs
tools/standalone/Standalone/Chainweb.hs

This PR adds an endpoint that sends a stream of `BlockHeader`s as Server-Sent Events for consumption by our block explorer.
Can be tested with:
```
chainweb-node --chainweb-version=development --port=8082 --log-level=warn --header-stream
curl -k -v https://localhost:8082/chainweb/0.0/development/header/updates
```

Header Stream

---

src/Chainweb/Chainweb.hs
src/Chainweb/Pact/PactService.hs

This PR was deployed on `us1.tn1.chainweb.com` at 00:32. The node caught up ~10,000 blocks and joined consensus with the network within eight minutes.

Avoid rewind when input to LookupPactTxs is empty

---

src/Chainweb/Pact/RestAPI/Server.hs
test/Chainweb/Test/Pact/RemotePactTest.hs

This PR prevents Payloads that report the wrong `ChainwebVersion` to be rejected before even reaching the mempool.

Reject Payloads by Version Incompat

---

chainweb.cabal
src/Chainweb/BlockHeaderDB/RestAPI/Server.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/Utils.hs

This fixes some nondeterminism problems we've been seeing in tests and obliterates our use of `sleep` when retrying!

Use sane retry logic in pact remote tests

---

src/Chainweb/Mempool/InMem.hs

This PR detects empty Vectors entering the validation logic and exits before redundant checks involving IO are performed. This better suits the low/no TX volume case.

Mempool Validation: Detect Empty Vectors

---

src/Chainweb/Miner/Core.hs

This PR avoids `succ` in the core mining loop. `succ` is implemented as follows for `Word`:
```haskell
instance Enum Word where
succ x
| x /= maxBound = x + 1
| otherwise     = succError "Word"
```
Our core mining loop doesn't care if the `Word` overflows, so all these `maxBound` comparisons are wasteful.

Avoid `succ`

---

miner/Miner.hs

Much better. This is with 3 cores:
```
2019-10-21 09:44:07.874889: [info] Starting Miner.
2019-10-21 09:44:57.432390: [info] Chain 3: Mined block at Height 5619. (2.61 MH/s)
2019-10-21 09:45:55.567942: [info] Chain 3: Mined block at Height 5619. (3.08 MH/s)
2019-10-21 09:46:39.591234: [info] Chain 1: Mined block at Height 5620. (3.14 MH/s)
```

Correct reported Hash Rates

---

src/Chainweb/Pact/TransactionExec.hs

Most likely reason for massive slowdown with transfer cmds

Fix busted module caching in buyGas

---

src/Chainweb/BlockHeaderDB/RestAPI.hs
src/Chainweb/CutDB/RestAPI.hs
src/P2P/Node/RestAPI.hs

With this change chainweb builds both with the released servant-0.16 versions *and* the current head of the `master` branch of servant.

Forward compatiblity with servant master

---

src/Chainweb/Mempool/Consensus.hs
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Pact/Service/PactInProcApi.hs
test/Chainweb/Test/Mempool/Consensus.hs

When resolving a fork, there's no reason to reintroduce transactions to the mempool that would already be expired if they were played now.

[mempool] don't reintroduce old transactions

---

src/Chainweb/Chainweb/PeerResources.hs

This reverts commit cf5775b5dde29ea79159dffed784a44c4de04207.
@gregorycollins this is temporary so that another fix can go in first.

Revert "Turn off tls cert checking on outgoing connections (#678)"

---

src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/Service/Types.hs

This limits rewinds on new block to a difference of 8 blockheight from checkpointer head. It also notes that the SPV use of checkpointer rewind needs to go away soon.

Only allow small rewinds on new block

---

src/Chainweb/Chainweb.hs
src/Chainweb/Cut.hs
src/Chainweb/CutDB.hs
src/P2P/Node.hs
src/P2P/Node/Configuration.hs
src/P2P/Node/PeerDB.hs
tools/genconf/GenConf.hs

* `private: true`: prevents the addition of any new peers to the PeerDb. The only peers that a private node connects to are the configured known peers. With this PR other nodes can still push cuts to a private node. PR #681 prevents unknown peers from pushing cuts.
* `initialCutHeightLimit`: When switching between forks, long rewinds are very expensive. Another issue is that a node that switches from fork `A` to `B` will go to `B` at a height larger than the current height an `A`. If the fork point is deep down it will attempt to do this in a single step, which might cause timeouts during rewind or pact replay (which doesn't cache intermediate states).
This PR allows the user to provide an estimate of the fork point or any lower bound (0 is always a safe, but inefficient choice), to cause …

Initial cut height limit and private flag

---

CHANGELOG.md
src/Chainweb/Chainweb/MinerResources.hs
src/Chainweb/Miner/Config.hs

The `coordination` config section now looks like:
```yaml
mining:
coordination:
enabled: false
mode: private
limit: 1200  # New field. The number of work requests allowed over a 5 minute period.
miners: []
```

Configurable Work Request Limit

---

src/Chainweb/Miner/Pact.hs
stack.yaml

This PR checks whether Pact `PublicKey`s parsed on the command line have the expected format.
Output from the miner:
```
option --miner-key: Public Key hamburger is not valid.
```

Parsing Public Keys

---

src/Chainweb/Logging/Config.hs

Eventually, amberdata should be remove from the consensus nodes (or at least be put behind a cabal flag). This PR is a first step in this direction.

hide amberdata configuration

---

src/Chainweb/RestAPI.hs
src/Chainweb/RestAPI/Utils.hs

The X-Chainweb-Node-Version header is already included in responses. The PR also adds it to requests.
The header is not mandatory and the change is fully backward compatible.
At this point, the header value is used only for monitoring purposes. Using this header for excluding certain node versions from the network should generally be avoided, since this can lead to forks in the network. However, there may be situations where this could be an effective tool for stabilizing the network. So, it's good to have it in place in case it's needed.

Inject X-Chainweb-Node-Version header in requests

---

src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
test/Chainweb/Test/Pact/Utils.hs

This seeds every module cache with the modules/interfaces loaded at genesis, keeping it in Pact Service state in perpetuity.

Seed Initial Module Cache in Pact Service at Genesis

---

node/ChainwebNode.hs
src/Chainweb/Logging/Miner.hs
src/Chainweb/Miner/Coordinator.hs

This moves logging of errors related to orphans into its own index for easier debugging.

Logging of Orphans

---

src/Chainweb/CutDB.hs
src/Chainweb/SPV/VerifyProof.hs

improve cut db member ship queries

---

src/Chainweb/Miner/RestAPI/Server.hs

If people send malformed data to `/mining/solved`, this will give shed more light onto why the decoding failed.

Catch decoding errors in /mining/solved

---

chainweb.cabal
src/Chainweb/Pact/Templates.hs
src/Chainweb/Pact/TransactionExec.hs
test/Chainweb/Test/CoinContract.hs

Gets a ~1ms savings per tx, and ~3ms per block
Before:
```
benchmarking PactService/block-new-valid[1]
time                 264.2 ms   (262.9 ms .. 265.3 ms)
benchmarking PactService/block-new-valid[10]
time                 309.0 ms   (296.8 ms .. 325.9 ms)
benchmarking PactService/block-new-valid[50]
time                 506.9 ms   (497.7 ms .. 514.7 ms)
benchmarking PactService/block-new-valid[100]
time                 742.6 ms   (705.6 ms .. 778.2 ms)
benchmarking PactService/block-new[1]
time                 134.1 ms   (132.9 ms .. 135.8 ms)
benchmarking PactService/block-new[10]
time                 158.8 ms   (156.8 ms .. 163.9 ms)
benchmarking PactService/block-new[50]
time                 247.4 ms   (242.8 ms .. 251.0 ms)
benchmarking PactService/block-new[100]
time …
```

Introduce "pre-compiled" terms for buy gas, coinbase

---

src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Transaction.hs
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/SPV.hs
test/Chainweb/Test/Pact/Utils.hs

This addresses a bug in the tx exec logic which failed to reward miners in the case of payloads that failed for whatever reason.

[Bugfix] Reward Miner For Failed Payloads

---

chainweb.cabal
src/Chainweb/Pact/Templates.hs

Should resolve replay issue, was able to reproduce JSON output on a bad coinbase:
```  Chainweb.Test.Pact.PactExec
testBadMinerFails: {
"Right": {
"gas": 0,
"result": {
"status": "failure",
"error": {
"callStack": [
"<interactive>:0:11303: (enforce (native `=`  Compare alike terms for equality, ret... \"account guards do not match\")",
"<interactive>:0:11175: (bind: [balance:<af> 100000000.0, retg:<ag> KeySet {keys: [368820f80c324bbc7c2b0610688a7da43e3...])",
"<interactive>:0:11088: (with-default-read (deftable coin-table:(defschema coin-schema \"The c... \"sender00\" {\"balance\": 0.0,\"guard\": KeySet {keys: [skdjhfskj]... ({balance:<af> \"balance\",retg:<ag> \"guard\"} [(nati...)",
"<interactive>:0:9096: (credit \"sender00\" KeySet {keys: [skdjhfskj],pred: bad} 2.304523)", …
```

Restore infos on pre-compiled terms

---

src/P2P/Node.hs
src/P2P/Node/PeerDB.hs

prune peer db and update peer selection

---

src/Chainweb/BlockHeader.hs
src/Chainweb/Chainweb/MinerResources.hs
src/Chainweb/Cut/Test.hs
src/Chainweb/Miner/Config.hs
src/Chainweb/Miner/Coordinator.hs
src/Chainweb/Miner/Miners.hs
src/Chainweb/Miner/RestAPI/Server.hs
src/Chainweb/Pact/Backend/ForkingBench.hs
src/Chainweb/Utils.hs
test/Chainweb/Test/Pact/ChainData.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/PactReplay.hs
test/Chainweb/Test/Pact/TTL.hs
test/Chainweb/Test/RestAPI.hs
test/Chainweb/Test/Utils.hs

This PR allows a Node to set a list of "blessed" Miner identities. Each such miner will have Payloads preformed for it, such that new work requests will return (almost) immediately without incurring the usual costs of going through `_pactNewBlock`.
**Note:** As is, this PR breaks existing configurations! What was previously:
```yaml
miners:
- abc123  # just an account name
- zxy098
```
Must now be:
```yaml
miners:
- account: abc123
predicate: keys-all
public-keys:
- 3438e5bcfd086c5eeee1a2f227b7624df889773e00bd623babf5fc72c8f9aa63
- account: zxy098
predicate: keys-all
public-keys:
- cfd7816f15bd9413e5163308e18bf1b13925f3182aeac9b30ed303e8571ce997
```
It honestly should have been this shape from the beginning.
Closes #598

Primed Mining Coordination

---

src/Chainweb/Pact/TransactionExec.hs

This was not caught in testing because `DevNet` fork time was set to `epoch`, and `def` for public meta's tx creation time is 0 - also `epoch`. These changes will make use of whatever the block time in the public data is from the header of the previous block of the current one.

Use block time instead of tx creation time

---

src/Chainweb/Miner/Coordinator.hs
src/Chainweb/Miner/Miners.hs
src/Chainweb/Miner/RestAPI/Server.hs

This PR alters the coordinator to give preferential treatment to any whitelisted miner in the `miners` list, regardless of the public/private mining scheme.

Primed Coordination for all Whitelisted Miners

---

src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Version.hs
test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs

Caveats:
- only loads `ns` and `coin`, whereas the previous solution also loaded `gas-payer-v1` and `fungible-v1`. Since this changes at upgrade, thought to go conservative for now. We can consider an `Interpreter`-based approach that pokes around more deeply, loading any module in the default namespace.
- Simple equality didn't work for testing the modules loaded from the PactDb vs loaded from genesis. However the module hashes match, so the test checks that.

Load default modules from pact db

---

node/ChainwebNode.hs

`Data.Text.IO.putStrLn` makes one write system call for each character when buffering is disabled. The reason for (or benefit of) that is unclear.
Even when other backends are in use, chainweb node still writes logging-system errors to stderr (e.g. when the logging backend fails). With elasticsearch this can happen, if the cluster reaches is capacity limits or in case of network connection hiccups. Those logs shouldn't be buffered too long in order to makes sure they are not lost in case of a node crash, since these logs may contain important debugging information.
However, the logging-system error logs are mostly short new-line terminated messages that are likely to be writing in a single system. So doing line buffering is fine in this case.

Set line buffering for stderr

---

src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs

Big improvement 
```
benchmarking PactService/forkingBench
time                 506.3 ms   (486.9 ms .. 529.5 ms)
benchmarking PactService/block-new-valid[1]
time                 7.792 ms   (7.619 ms .. 7.953 ms)
benchmarking PactService/block-new-valid[10]
time                 52.66 ms   (50.48 ms .. 54.22 ms)
benchmarking PactService/block-new-valid[50]
time                 251.3 ms   (233.6 ms .. 268.1 ms)
benchmarking PactService/block-new-valid[100]
time                 483.7 ms   (459.9 ms .. 507.3 ms)
benchmarking PactService/block-new[1]
time                 3.420 ms   (3.371 ms .. 3.476 ms)
benchmarking PactService/block-new[10]
time                 26.44 ms   (26.19 ms .. 26.78 ms)
benchmarking PactService/block-new[50]
time                 128.4 ms   (124.7 ms .. 131.3 ms) …
```

Fix coinbase caching

---

.github/workflows/applications.yml
test/Chainweb/Test/Pact/SPV.hs

The mining calculations were wrong - this makes sure that enough blocks are mined between phases of the SPV txs so that consensus is achieved. `RemotePactTest` bumped its timeout backoff rate in #866, which should fix the polling timeouts that were contributing to the tests failing. 
Unfortunately, I have no clue how to fix the `PactReplay` tests. It looks like a wait time problem.

Fix SPV Test Nondeterminism

---

chainweb.cabal
overrides.nix
tools/header-dump/HeaderDump.hs

This unifies the output format across different output types:
```json
{
"chainId": INT,
"height": INT,
"data": OBJECT
}
```

improve header dump tool

---

src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Pact/Backend/ForkingBench.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/PactInProcApi.hs
src/Chainweb/Pact/Types.hs
test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs
test/Chainweb/Test/Pact/Utils.hs
test/Chainweb/Test/TreeDB.hs
tools/ea/Ea.hs
tools/standalone/Standalone/Chainweb.hs

Normally, payload hashes are validated only for blocks for which validation is requested, but not for possible checkpointer replays. Normally that is fine because normally we trust the existing databases. But sometimes we want to be extra pedantic.
Moreover, when rebuilding a pact database from an existing chain database (or each time we start with a pact db that is "behind" the latest cut of the chaindb), the pact does an initial database sync during which the payload hashes must be revalidated. 
Ideally, we would always enable pedantic hash validation during the initial sync and possibly disable it afterwards. But for that we would have to extend the pact service API to support enabling and disabling pedantic checks. Which which would be a large change that would involve some API design …

Add configuration options for checking payload hashes during pact replay

---

chainweb.cabal
stack.yaml

This is an experimental PR to see how usage of the `network-2.8` series affects our node stability.
---
After a number of lengthy experiments, we now believe the issue to be a regression introduced in `network-3.1.1.0`. Our official Ubuntu builds will now avoid that version until this has been fixed upstream.

Bound the `network` Dependency

---

chainweb.cabal

This should actually be fixed in pact. Until then we put this in chainweb as a temporary solution.
We add this to `chainweb.cabal` (as opposed to adding constraints to `cabal.project`, `overwrites.nix`, and `stack.yaml`), because this isn't about build dependencies, but about actual semantic correctness of the chainweb.

fix prettyprinter version to 1.6.0

---

.github/workflows/applications.yml

On the github runners this currently takes about 50 minutes. There are different ways how this could be made faster. But we run these builds only for merges to master, so I think, 1h build time would be fine for now.
The S3 executables are uploaded before the the history validation runs, so those are available within about 10min.
An alternative approach is to run history validation on a fixed schedule, say, every two hours, using the latest master build chainweb-node binary from the S3 bucket.

Do full pact validation of mainnet history as part of GitHub ci  workflow

---

chainweb.cabal
src/Chainweb/BlockHeader.hs
src/Chainweb/BlockHeader/Validation.hs
src/Chainweb/Version.hs
test/Chainweb/Test/BlockHeader/Validation.hs
test/ChainwebTests.hs

Currently master is broken for mainet01. We must merge either this PR or #920 to unbreak it.
This is a technical non-user facing fork.  It affects only miners which would have to migrate "buggy" miners before that block height.
We therefor avoid the extra complexity involved with basing it on a date and use a block height instead -- which is also easier to handle for miners.
The block height is chosen to give miners about 5 days after the release of 1.6 to adapt their mining clients as needed. It is also expected to occur on a Monday during US office hours.

grandfather non-zero feature flags for block heights < 340000

---

cabal.project
project.nix
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
stack.yaml
test/Chainweb/Test/Pact/Checkpointer.hs
test/Chainweb/Test/Pact/TransactionTests.hs

Will leave forking config for after #915 goes in, so this just ups the pin and gets chainweb building.

Pact bump for execution config flags, enforce-one fix

---

.github/workflows/applications.yml
tools/header-dump/HeaderDump.hs

I'll plan to build an standalone database validation tool based on this, that would also include the functionality for validating the pact database and cuts.
For now, the fastest route to implement header validation for a db was to add it to the header-dump tool. It also makes sense to as a feature of this tool.

add --validate flag and output type none to header-dump

---

src/Chainweb/Version.hs
test/Chainweb/Test/BlockHeader/Validation.hs

Permanently disable validation of feature flags for `Mainnet01`, `Testnet04`, and `Development`. Validation is enabled for test chainweb versions.

keep feature flag validation disabled

---

src/Chainweb/BlockHeader.hs
src/Chainweb/Chainweb/MinerResources.hs
src/Chainweb/Crypto/MerkleLog.hs
src/Chainweb/Miner/Coordinator.hs
src/Chainweb/Pact/Backend/ForkingBench.hs
src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/BlockValidation.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Utils.hs
src/Chainweb/Payload.hs
src/Chainweb/Version.hs
src/Chainweb/WebPactExecutionService.hs
test/Chainweb/Test/CutDB.hs
test/Chainweb/Test/Pact/ChainData.hs
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/PactReplay.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/SPV.hs
test/Chainweb/Test/Pact/TTL.hs
test/Chainweb/Test/Pact/TransactionTests.hs
test/Chainweb/Test/Pact/Utils.hs

In the current code base the block creation time of the *current* header is used as reference for tx timing validation. The current time during pact validation is the block creation time of the *parent* header is used.
This PR provides the first step of resolving this inconsistency. The PR
The line of changes from this PR is continued in #942

Creation time fix [Phase 1]

---

src/Chainweb/Mempool/InMem.hs
test/Chainweb/Test/Mempool.hs

Issue was `mempoolClear` not clearing everything between tests (namely `_inmemCountPending` but also bad map) so quickcheck would intermittently overfill past `maxNumPending`.
This wouldn't affect production as `mempoolClear` is indicated as only being for testing (https://github.com/kadena-io/chainweb-node/blob/059ff64b4d8290ec1606a1d37ff0ff007e8e315f/src/Chainweb/Mempool/Mempool.hs#L270-L272)

Fix mempool highwater test

---

cabal.project
src/Chainweb/Mempool/InMemTypes.hs
src/Chainweb/Pact/Backend/ChainwebPactDb.hs
src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Types.hs
src/Network/X509/SelfSigned.hs
tools/run-nodes/RunNodes.hs

Fix incomplete pattern matches in `IO` and get the code base ready for GHC-8.8.

Get rid of MonadFail from IO

---

src/Chainweb/Pact/Backend/Types.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/Utils.hs
test/Chainweb/Test/Utils.hs

Gets rid of `adminData` and `goldenTestTransactions` in Pact test utils too

Better test mempool fixture; overhaul PactInProcAPI

---

src/Chainweb/Mempool/InMem.hs
src/Chainweb/Pact/Backend/ForkingBench.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Utils.hs
src/Chainweb/Time.hs
src/Chainweb/Version.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/TTL.hs
test/Chainweb/Test/Pact/Utils.hs
tools/ea/Ea.hs

The current issue we face is, due to using parent time for transaction validation, the following scenario fails:
1. Parent time: 00:00:00
2. Tx time: 00:00:15
3. New block time: 00:00:30
The transaction will not be accepted, even though the tx time is fully valid. It is rejected in `timingsCheck`, specifically that the tx creation time is strictly before the `txValidationTime` (https://github.com/kadena-io/chainweb-node/blob/ea1c8d1c5759d79b455efb2c625320cd12aeebbf/src/Chainweb/Pact/Utils.hs#L85), in all three places:
- pre-insert check into mempool (txValidationTime == parentHeader time)
- new-block validation (txValidationTime == parentHeader time)
- validate-block validation (txValidationTime == parentHeader time)
This PR proposes the following solution:
1. Pre-insert check uses …

Fix creationTime Issue with new creation-time code

---

src/Chainweb/BlockHeader.hs
src/Chainweb/Version.hs

This shifts the computation of the epoch time back one block, so that the computation of the target doesn’t depend on the creation time of the current block.
Legacy behavior is guarded by `oldTargetGuard` and switched on for `Mainnet01` and `Testnet04`. It's on for `Development` for block `< 360`.
When the guard switches of there is one epoch that has only 119 blocks. There is no need to adjust target computation, because change in the overall epoch time are minimal.

compute epoch time based on parent header

---

src/Chainweb/RestAPI.hs

This fixes the original issue described in #800, the missing swagger entry for the cut endpoint.

add missing cut api to swagger endpoint

---

src/Chainweb/Cut.hs
src/Chainweb/CutDB.hs

We generally trust the chain db. Let's also trust the cut that is persisted in the DB.

Omit joining initial cut from CutDB with genesis cut

---

.github/workflows/applications.yml
src/Chainweb/BlockHeader.hs
src/Chainweb/BlockHeader/Genesis.hs
src/Chainweb/Crypto/MerkleLog.hs
src/Chainweb/MerkleUniverse.hs
src/Chainweb/SPV/CreateProof.hs
test/Chainweb/Test/BlockHeader/Validation.hs
test/Chainweb/Test/Mempool/Consensus.hs
test/Chainweb/Test/Orphans/Internal.hs
test/Chainweb/Test/Utils.hs

This fixes #960. The former PR switched the names for feature flags and nonce. This was done in a way that the binary encoding and the Merkel root for old headers was unchanged.
However, the types of the Merkel tree entries guid the selection of leaf position of proof subject during proof creation. Thus proof creation would look for the subject in the wrong place in the tree.
This PR also switches the types of flags and nonce (and the tags in the MerkleUniverse) in the Merkel tree.

Switch flags and nonce in Merke tree

---

CHANGELOG.md
chainweb.cabal
src/P2P/Node.hs
src/P2P/Node/Configuration.hs
src/P2P/Node/PeerDB.hs
test/Chainweb/Test/Orphans/Internal.hs
test/ChainwebTests.hs
tools/run-nodes/RunNodes.hs

Remove redundant stuff

---

chainweb.cabal
test/Chainweb/Test/SPV.hs

The only remaining use of reflection was actually redundant. 
Most changes in this PR are just whitespace changes do to reindentation of a function body `test/Chainweb/Test/SPV.hs`.

get rid of reflection

---

src/Chainweb/Pact/Backend/ForkingBench.hs

In order to make devnet start reliably we had to lower the initial target. Using a non-trivial target however, slows down benchmarks that use chainweb version `Development`.

avoid use of Development in bench marks

---

src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/TransactionTests.hs
test/Chainweb/Test/Pact/Utils.hs

Cleanup PactService state to simply track parent header, use new `TxContext` to pair this with `PublicMeta` from tx, `PublicData` only assembled at actual tx execution

Unify PactService on parent header

---

src/Chainweb/RestAPI.hs
src/Chainweb/Rosetta/RestAPI.hs
src/Chainweb/Rosetta/RestAPI/Server.hs

Adds Rosetta's network endpoints

---

src/Chainweb/Pact/Backend/ChainwebPactDb.hs
src/Chainweb/Pact/Backend/InMemoryCheckpointer.hs
src/Chainweb/Pact/Backend/RelationalCheckpointer.hs
src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/BlockValidation.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/WebPactExecutionService.hs
test/Chainweb/Test/CutDB.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/TransactionTests.hs
test/Chainweb/Test/Pact/Utils.hs

Provide full txlog history for a block via `WebPactExecutionService`

Pact block history query

---

src/Chainweb/Miner/Pact.hs
src/Chainweb/Pact/PactService.hs
test/Chainweb/Test/Pact/RewardsTest.hs
test/Chainweb/Test/Pact/Utils.hs

Instead of just pre-calculating miner rewards, expecting the order of the chain graph to remain fixed, this PR moves the graph-order calculation out to the `minerReward` function, so that we can calculate the division on the fly.

Make miner reward calculation graph order aware

---

src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs

This fix makes `/local` endpoint calls more correct, with public data that references: 
- parent header creation time
- previous block hash (which is the parent hash, instead of grandparent)
- current block height

Fix PublicData for /local

---

src/Chainweb/Pact/PactService.hs

Resolves `TreeDbKeyNotFound` issues in `local` and mempool pre-insert check, by using `PactService` parent header in cache. 
Adds an extra update to the cache after block validation to set the "parent" to the just-validated current block.

Remove header lookup from local, pre-insert check

---

chainweb.cabal

Pact inlines error messages from base64-bytestring via `Show` in internal pact errors.
There is the following change in base64-byestring-1.1.0:
```diff
- Base64DecodeException "invalid base64 encoding near offset 0" 
+ Base64DecodeException "invalid character at offset: 0"
```
which would break mainnet history. Until we have a long term fix, we'll put an upper bound on base64-bytestring.

add upper bound for base64-bytestring

---

chainweb.cabal
tools/ea/Ea.hs
tools/run-nodes/RunNodes.hs

the combination of `NoImplicitPrelude` and `base-prelude` was resulted in a bad `toList` instance for `Maybe` (possibly related to a bad `IsList` instance for `OverloadedLists`, but I didn't investigate it further).
This tiny PR drops the dependency on `base-prelude`.

remove broken base-prelude dependency

---

test/Chainweb/Test/Pact/TransactionTests.hs
test/pact/twenty-chain-insufficient-bal.repl

This test proves that if e7f7 is underfunded, then the service will not fail at remediation time (tested for Devnet)

Add test for 20-chain remediation pass-through

---

src/Chainweb/Rosetta/Internal.hs
src/Chainweb/Rosetta/RestAPI/Server.hs

`/network/list` was returning networkIds with chain ids that were not active yet. This caused an error when querying `/network/status` with these inactive chain ids.
Fixes https://github.com/kadena-io/chainweb-node/issues/1116

[Bug Fix] Only return active chain ids in Rosetta NetworkId

---

src/Chainweb/BlockHeaderDB/PruneForks.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/TreeDB.hs
test/Chainweb/Test/Pact/PactReplay.hs
test/Chainweb/Test/Pact/Utils.hs

If the latest block that is stored in the checkpointer gets orphaned after the service is stopped, pact service fails on startup. This PR fixes this by rewinding on startup to the latest block in the checkpointer block history that is available header in the block header db.
Some fixes and cleanups around the use of '_psParentHeader' and the use of the checkpointer are included in this PR, which was helpful for debugging and resolving the issue.
These are the changes in detail:

rewind pact service initially to lastest available header in history

---

bench/Chainweb/Pact/Backend/ForkingBench.hs
chainweb.cabal
src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/Backend/Utils.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/PactService/Checkpointer.hs
src/Chainweb/Pact/PactService/ExecBlock.hs
src/Chainweb/Pact/Service/PactInProcApi.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/RewardsTest.hs
tools/ea/Ea.hs

Motivated by wanting Checkpointer interactions in a submodule, `ExecBlock` submodule became necessary for shared deps, and moved other things into various Types and Utils modules.

PactService module cleanup

---

src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/PactService/ExecBlock.hs
src/Chainweb/Pact/Utils.hs
src/Chainweb/Version.hs
test/Chainweb/Test/Pact/TTL.hs

This PR simplifies the tx timing validation code.
Early versions of chainweb used the creation time of the current block header for timing validation. Recent version use the parent creation time. Special logic was needed during the transition period, which now can be removed.
In addition to removing transition code, this PR also simplifies the handling of old blocks. Since, once a tx passes timing validation, it has no further effect on the pact validation of the tx, it is possible to just skip the timing validation for historic blocks.

Remove legacy tx timing validation code

---

chainweb.cabal
src/Chainweb/Chainweb.hs
src/Chainweb/Mempool/CurrentTxIndex.hs
src/Chainweb/Mempool/CurrentTxs.hs
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Mempool/InMemTypes.hs
src/Chainweb/Mempool/Mempool.hs
src/Chainweb/Mempool/RestAPI.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/PactInProcApi.hs
test/Chainweb/Test/Mempool/InMem.hs
test/Chainweb/Test/Mempool/RestAPI.hs
test/Chainweb/Test/Mempool/Sync.hs
test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs
test/Chainweb/Test/Pact/Utils.hs

This PR addresses two issues with the current Mempool:
1.  The mempool currently only deletes transactions that are included in a new block from the list of pending transactions in calls of `execNewBlock`. That means that transactions are removed from the pending set only on nodes that are mining.
The PR adds the respective calls of
```Haskell
mpaProcessFork memPoolAccess p
mpaSetLastHeader memPoolAccess p
```
to `execValidateBlock`. `p` is the parent header of the currently validate header. This isn't optimal. Ideally, the transactions in the current header should be removed, too. However, the implementation of these functions of the mempool accesses the payload db in order to obtain the transactions of the block. At the time these calls are made the current block is generally not yet …

Update mempool after execValidateBlock and keep track of committed txs

---

cabal.project
dep/kpkgs/github.json
src/Chainweb/Pact/NoCoinbase.hs
src/Chainweb/Pact/SPV.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
src/Chainweb/Version.hs
stack.yaml
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/TransactionTests.hs

Forking change to support Pact Events (https://github.com/kadena-io/pact/pull/819) in output for SPV proofs etc.
TODOs:

Support Pact Events

---

cabal.project
chainweb.cabal
dep/kpkgs/github.json
src/Chainweb/Pact/NoCoinbase.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
src/Chainweb/Version.hs
stack.yaml
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/TransactionTests.hs

Retry of #1150 with better back-compat.
Picking block heights might need to wait for 2.3 release. @larskuhtz @mightybyte how should we track? Also we need a mainnet replay.
Only way to test with Chainweaver etc IMO is in devnet, however this build should deploy into testnet/prod without disturbance with the current blockheights, so can at least verify that `local` backcompat is not broken.

Pact Events redux

---

.github/actions/install-chainweb-from-artifacts/action.yml
.github/workflows/applications.yml
.github/workflows/stack-ci.yaml

This PR addresses: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

Update GitHub actions

---

src/Chainweb/Pact/TransactionExec.hs

This PR ensures that fungible-v2 is included in the module cache after calling `applyUpgrade`. 
Perviously fungible-v2 was missing from psInitCache and would be added only after the next restart of pactService. This could break history replays or catchups (that started replay from before the upgrade).

fix applyUpgrades to correctly update psInitCache

---

chainweb.cabal

Previous version of network the package (>= 3.1.1.0) had a bug that could cause nodes to stall after running for several days. The issue is reported here: https://github.com/haskell/network/issues/438.
Version [3.1.2.0 of the network package](https://github.com/haskell/network/releases/tag/v3.1.2.0) is supposed to fix this and we haven't observed the issue while testing this branch, which indicates that the issue is indeed fixed.

remove upper bound on network

---

.github/workflows/applications.yml
cabal.project

use http-client-0.7.5 in cabal builds

---

CHANGELOG.md
chainweb.cabal
node/ChainwebNode.hs

bump version to 2.5 and update kill-switch and changelog

---

cabal.project

This bound should be moved into pact.cabal. But for now, we enforce it here.

enforce upper bound on prettyprinter

---

src/Chainweb/BlockHeaderDB.hs
src/Chainweb/BlockHeaderDB/Internal.hs

`seekTreeDb` is unsafe, since it returns an iterator that must be released explicitly. There is an `withSeeTreeDb` function that should be used instead.

do not export seekTreeDb

---

src/Chainweb/Pact/RestAPI/Server.hs

Increase the listen timeout in the chainweb-node from 2min to 3min.

increase default listen timeoutto 3 minutes

---

src/Chainweb/Miner/Coordinator.hs

This fixes a condition in the newWork method that cause the mining coordinator to get stuck on an outdated primed work item.

fix mining newWork function

---

chainweb.cabal
src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Chainweb/CheckReachability.hs
src/Chainweb/Chainweb/MempoolSyncClient.hs
src/Chainweb/Chainweb/PeerResources.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/RestAPI.hs
src/Chainweb/Rosetta/RestAPI/Server.hs
src/P2P/Node.hs
src/P2P/Node/Configuration.hs
src/P2P/Node/PeerDB.hs
src/P2P/Node/RestAPI/Client.hs
src/P2P/Node/RestAPI/Server.hs
test/Chainweb/Test/MultiNode.hs

This PR involves some long pending code cleanup in order to avoid cyclic dependencies. While touches a lot of code the changes are mostly straight forward.

Avoid injecting the local peer into the peer db

---

src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/PeerResources.hs
src/Chainweb/RestAPI.hs
src/P2P/Node/Configuration.hs
test/Chainweb/Test/Orphans/Internal.hs

Allow an expert user to run the peer API of an chainweb-node without TLS behind a reverse proxy.

Hidden option to disable TLS for peer API

---

src/P2P/Peer.hs

Configuring the P2P hostname as `0.0.0.0` causes automatic configuration of the Hostname, which is a reasonable default behavior.

Set 0.0.0.0 as default P2P hostname

---

node/ChainwebNode.hs
src/Chainweb/Chainweb/PeerResources.hs
src/Chainweb/CutDB.hs
src/Chainweb/Pact/PactService/Checkpointer.hs
src/Chainweb/Pact/Service/PactInProcApi.hs
src/Chainweb/Utils.hs
src/Control/Concurrent/FixedThreadPool.hs
src/P2P/Node.hs
test/Chainweb/Test/Mempool/RestAPI.hs

GHC-9 is a bit less lenient and requires more explicit eta expansions.
Also, base-4.15 comes with `Generic` instances for `GCDetails` and `RTSStats`. So, we can omit the orphan instances.

a few eta-expansions for ghc-9

---

CHANGELOG.md
chainweb.cabal
node/ChainwebNode.hs

Bumps the killswitch date by 8 weeks, i.e. Thursday, 2021-10-14.
TODO:

Version 2.9

---

.github/workflows/applications.yml

Ci/fix 8.8.4 build

---

cabal.project
chainweb.cabal
project.nix
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Version.hs

Enables pact flag to enforce valid keys in `read-keyset`. Before the switch any key value used in `read-keyset` will succeed; after, only valid Pact public key values will work.
Development block height is 100.

Enforce keyset formats

---

chainweb.cabal
src/Chainweb/Crypto/MerkleLog.hs
src/Chainweb/Payload/RestAPI/Server.hs
src/Chainweb/RestAPI/NetworkID.hs
src/Chainweb/Utils.hs
src/Servant/Client_.hs
test/Chainweb/Test/Cut.hs
test/Chainweb/Test/Orphans/Internal.hs
test/Chainweb/Test/Utils.hs
test/Chainweb/Test/Utils/TestHeader.hs

Remove some legacy CPP macros and lower bounds that are now obsolete since the nix builds use GHC-8.10.

remove legacy CPP macros and raise lower bounds

---

chainweb.cabal

[0.2.16.0 added this](https://github.com/haskell-unordered-containers/unordered-containers/pull/317) which probably totally breaks everything.

Tighter bound on unordered-containers

---

node/ChainwebNode.hs

It seems that `checkpointRocksDb` expects that the directory where the checkpoint is created exists. This PR creates `checkpointDir` if it doesn't already exist.
Tested on testnet (us1.testnet.chainweb.com)

create rocksDbCheckpoints directory if needed

---

src/Chainweb/Pact/Service/PactInProcApi.hs
src/Chainweb/Pact/Service/PactQueue.hs

This PR has been tested on testnet.

Fix and cleanup PactQueue Statistics Logging

---

.github/workflows/applications.yml

Fixes the output of `chainweb-node --long-info`, which contains unicode characters.

set locale to en_US.utf-8 in container images

---

src/Chainweb/CutDB.hs
src/Chainweb/Sync/WebBlockHeaderStore.hs

The changes in `src/Chainweb/CutDB.hs` are just formatting.
The only functional change is in `src/Chainweb/Sync/WebBlockHeaderStore.hs`

query block headers from local db before remote

---

bench/Chainweb/Pact/Backend/Bench.hs
bench/Chainweb/Pact/Backend/ForkingBench.hs
chainweb.cabal
src/Chainweb/Pact/Backend/Utils.hs
test/Chainweb/Test/Pact/Checkpointer.hs
test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/PactInProcApi.hs
test/Chainweb/Test/Pact/Utils.hs
test/Chainweb/Test/Utils.hs
tools/db-checksum/CheckpointerDBChecksum.hs

SQLite has built-in support for temporary (and in-memory) database. When the database file is the empty string, a temporary database file is used that is removed when the connection is closed (cf. https://www.sqlite.org/inmemorydb.html).
The PR does the following:
* Simplify test code by using sqlite's built-in support for temporary database files.
* Remove the used `todelete` flag from `withSQLiteConnection`
* Drop dependency on `extra` package by using temporary directory creation form the `temporary` package

cleap use of temporary sqlite databases in tests

---

src/Chainweb/CutDB.hs

That `min 0` made it in at the last minute, should've been tested again.

Fix reset to block height

---

default.nix
dep/pact/github.json

This PR depends on https://github.com/kadena-io/pact/pull/1004, which should probably be merged first so that this branch can continue to depend on Pact master.
This branch fixes a breakage introduced in fb91d52caaaaea6f928fd24f4dc66dc257716deb, since the Nix environment knew nothing about the `sha-validation` Haskell package, and the dependencies of that package were incompatible with the current Nix environment provided for `chainweb-node`.

Update Nix to include recently introduced sha-validation dependency

---

src/P2P/Node.hs

This PR is greatly motivated by the ideas and insights from #1470:
*   Moving the `_p2pConfigMaxSessionCount` check out of the fold will cause the transaction to fail early and prevent retrying the transaction for each single peer in the peer database.
Ideally this reduces the overhead of P2P session creation by a factor of that is equal to the number of peers in the peer database. The current median number of peers on mainnet nodes is 360.
*   The latest iteration of this PR uses STM only for awaiting a non-empty set of candidate peers. The actual peer selection is not transactional, which is supposed to greatly reduce contention.
*   Expensive transactional computations that are also less likely to fail and cause retries are moved towards the end of the STM transaction.
*   The PRNG is …

fail early during p2p peer selection

---

chainweb.cabal
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Pact/Backend/RelationalCheckpointer.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Utils.hs

I am pretty sure writing to an `unsafeThaw`ed vector is never safe, and there is no way for it to improve our performance here anyway... more likely it worsens our performance. I get not having `mutableVectorFromList` is annoying though, so I added that.
(see https://stackoverflow.com/questions/54041813/just-how-unsafe-are-data-vectors-unsafefreeze-unsafethaw)

Remove uses of unsafeThaw in the mempool and checkpointer

---

node/ChainwebNode.hs

I don't expect this to make a whole lot of a difference, but it should at least reduce the cost somewhat. In concrete it should reduce the number of rocksdb calls (and associated JSON decoding) by more than 50%. It also avoids some unneeded JSON encoding/decoding roundtrips.

Reduce overhead of txCount in block update monitor

---

chainweb.cabal
default.nix

This default.nix file uses Nix release 22.05 (May 2022) as its basis, with GHC 8.10.7 as the compiler, and setting version pins where necessary for compatibility with chainweb.cabal. It strives to keep overrides to a minimum, and to avoid disabling as many build-time checks as possible.
Running nix-build in the chainweb-node directory should produce a build that's very close to our Linux-based production build.

Build a proper default.nix with a modern nixpkgs pin

---

cabal.project

A new warp-tls has been released that works with the new warp version, making the CI fix from yesterday unnecessary.

Disable now-unnecessary warp bound

---

dep/pact/github.json

This is the nix counterpart to https://github.com/kadena-io/chainweb-node/commit/ead9b16dd3d407cd61c942b3cb464398f2e3ea64#diff-b8ed06757045fac949c89f2139a862498ad2b6d1f82c61a31e7c91d6cf0eaa70R57

Fix nix-build by updating pact to 4.4

---

src/Chainweb/Chainweb/Configuration.hs

Setting `initialBlockHeightLimit` in the config file was broken, this fixes it. A subtle cause; 
`optional $ BlockHeight <$> option Auto (long "initial-block-height-limit")` will *always succeed*, so if the CLI option is not provided, `Nothing` will override the existing config file flag.

Fix replaying via config file

---

src/Chainweb/Pact/Backend/Utils.hs
src/Chainweb/Pact/PactService.hs

`withSavepoint` here is trying to rethrow asynchronous exceptions but fails because it catches `AsyncException` instead of `SomeAsyncException`. I noticed this looking at the logs which show `non-pact exception: AsyncCancelled`.

withSavepoint now catches SomeAsyncException

---

src/Chainweb/Rosetta/Utils.hs

Transfers increased from 600 units to around 800 units. Hence, the hard coded cost of transfers in the Rosetta Construction API needs to increase as well.

Increases transfer cost variable used by Rosetta

---

cabal.project
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/PactService/ExecBlock.hs
src/Chainweb/Pact/RestAPI.hs
src/Chainweb/Pact/RestAPI/Client.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/Service/BlockValidation.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
src/Chainweb/Pact/Validations.hs
src/Chainweb/WebPactExecutionService.hs
test/Chainweb/Test/Pact/Checkpointer.hs
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/PactMultiChainTest.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/TransactionTests.hs
test/Chainweb/Test/RestAPI/Utils.hs
tools/cwtool/TxSimulator.hs

TODO: 
- Should we have enriched local output that is `CommandResult` when legacy is called, with warnings defined when preflight?

Add Warning System to `/local` preflight

---

src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/Pact/Validations.hs

Optional QOL improvements for `/local`.

Fix encoding wibbles in /local, return a list of validation failures

---

src/Chainweb/BlockHash.hs
src/Chainweb/BlockHeader.hs
src/Chainweb/Difficulty.hs
src/Chainweb/Payload.hs
src/Chainweb/PowHash.hs
src/Chainweb/Utils.hs

base64 text is already both a) valid UTF8 and b) escaped with respect to JSON. So why spend time encoding to UTF8, or escaping for JSON? This PR stops us doing that.

Optimize JSON+base64 encoding

---

cabal.project
chainweb.cabal
src/Chainweb/Chainweb.hs
test/Chainweb/Test/Utils.hs
test/Chainweb/Test/Utils/APIValidation.hs

Main purpose of the PR is to relax upper bounds that are introduced by dependencies of wai-middleware-validation.
The PR includes a few small changes along the way that, I think, improve readability and maintainability a bit.

relax bounds of wai-middleware-validation dependencies

---

test/Chainweb/Test/Pact/PactMultiChainTest.hs

Add tests for the upgrade to pact-4.7.

Test return value typechecking and read-* in try

---

tools/cwtool/TxSimulator.hs

Adds a `-t` flag to `cwtool tx-sim` to run static tc on every module on chain.
```
Stuarts-MBP-2:chainweb stuart$ cabal run cwtool -- tx-sim -d pactdbs -s 3299990 -c 2 -t | sort
TC_FAILURE: free.anedak-gas-station: Unable to resolve all types: 7 failures
TC_FAILURE: free.babena: Unable to resolve all types: 7 failures
TC_FAILURE: free.backalley-token: Unable to resolve all types: 3 failures
TC_FAILURE: free.backalley: Unable to resolve all types: 3 failures
TC_FAILURE: free.corona-inu: Unable to resolve all types: 8 failures
TC_FAILURE: free.dbc-token: Unable to resolve all types: 8 failures
TC_FAILURE: free.fin-us: Unable to resolve all types: 21 failures
TC_FAILURE: free.kDOGE: Unable to resolve all types: 1 failures
TC_FAILURE: free.kadena-mining-club: Unable to resolve all types: 45 …
```

Add typechecking option to tx-sim

---

cabal.project
default-flake.nix
flake.lock
flake.nix

This PR is an alternative to #1664. The main difference is that we bump the `hackage` snapshot by defining it as a direct input of our flake and telling `haskellNix` to `follow` it. The we can just `nix flake lock --update-input hackage` to bump the snapshot without actually bumping `haskell.nix`. I think this has 2 main advantages:
* Bumping `haskell.nix` may introduce unrelated changes to the build infrastructure. Changes one might not be willing to deal with just to bump the hackage snapshot.
* Bumping `haskell.nix` triggers a deeper transitive dependency rebuild session compared to just bumping `hackage`, which only requires a rebuild of the project's Haskell package dependencies. This can mean a 10-hour rebuild vs. a 2-hour rebuild.

Fix nix builds by ignoring freeze & bumping hackage

---

src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/Configuration.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/PactService/Checkpointer.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/Pact/Types.hs
test/Chainweb/Test/Pact/PactMultiChainTest.hs
test/Chainweb/Test/Pact/Utils.hs
tools/cwtool/TxSimulator.hs

This PR fixes the behaviour of `execLocal` functionality with a provided rewind depth parameter — it executes the transaction in the context of the block with the provided depth.

Add rewind depth support for execLocal

---

default.nix

@chessai Pointed out that the current `master` branch fails to build with `nix build -f . default`, even though our nix build setup is supposed to compute the same derivation for `nix build` and `nix build -f . default` (which is the same as `nix-build`). This PR removes a discrepancy in the way `haskellNix` is used in the non-flake call path, which used to cause `haskellNix` to pick up `hackage.nix` from its own `flake.lock`, which ended up ignoring our explicit `hackage.nix` input.

Avoid importing haskellNix directly in default.nix

---

src/Chainweb/Version/Development.hs
src/Chainweb/Version/Mainnet.hs
src/Chainweb/Version/Testnet.hs
test/Chainweb/Test/TestVersions.hs

A bad merge (or really bad merge order) made the `chainweb219Pact` block height revert to a placeholder. This works in partial replays of recent block history and on a mainnet node.

Fix chainweb219Pact heights

---

src/Chainweb/Pact/PactService.hs
test/Chainweb/Test/Pact/RemotePactTest.hs

This PR fixes the incorrect usage of current `TxContext`, making it use the rewinding `ParendHeader`. Also fixes the problem with using the current gas model.

Fix the bug with TxContext and current GasModel in /local

---

.github/workflows/nix.yml

This is so error messages don't get truncated, and we can get callstack/trace error messages

gha: verbose nix builds and --show-trace in case an error occurs

---

cabal.project

After merging #1709 the pact pin was pointing at pact PR https://github.com/kadena-io/pact/pull/1263. This PR is now merged to master and the PR updates the pact pin accordingly.

update pact pin to lastest master

---

chainweb.cabal
node/ChainwebNode.hs
src/Chainweb/RestAPI/Utils.hs

See https://well-typed.com/blog/2021/03/memory-return/, makes the OS' value for the RSS for chainweb-node more accurately reflect the actual used memory. Also adds our version of "idle GC" every 30 seconds, which gives the runtime more chances to return memory to the OS. Also make the socket listen queue size slightly smaller, as was probably originally intended.

Tiny fixes

---

node/ChainwebNode.hs

After acknowledging the issue with the service date and fixing the release calculator the service date still wasn't updated.

Update service date again

---

test/Chainweb/Test/MultiNode.hs

Noticed while adding a MultiNode test that replayTest only actually runs two nodes.

replayTest node count fix

---

.github/workflows/applications.yml

I want to use a merge queue!
I'm not sure if we need this PR per se, but https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions says so.

Enable applications workflow on merge_group event

---

.github/workflows/nix.yml
flake.nix

Summary: Add configuration for using the public S3 build cache in `nixConfig`, so all users get it OOTB with no effort. This is a much better experience than accidentally compiling 1 billion things on accident for the first time.
At some point, we might want to look at optimizing the cache itself (e.g. you can do a lot better in perf/price than raw S3), but that can come later since it only needs a URL change in practice.
Change-Id: I999da7a83317ad1bd83c8a521c43cff4

flake: explicitly configure public build cache by default in nixConfig

---

.github/workflows/applications.yml

As we've switched over to fast-development as the dev network for replays and integration tests, the existing replay steps aren't working.  This has updated parameters so that if we change the name again or add a new development network, we can change it in one place accurately.

update parameters for replay db

---

default.nix

Don't pick up `dist-newstyle`, and also include `haskell-language-server` in the default flake env.

nix: small tweaks

---

src/Chainweb/Pact/Backend/RelationalCheckpointer.hs
test/Chainweb/Test/Pact/RemotePactTest.hs

Summary: The INNER JOIN used to return the result set when looking up a transaction hash was `zip`'d without taking into account the ordering of the result set. This in turn meant that tx ID's got mapped to the wrong block IDs, resulting in lookup failures.
This could be reproduced with the following minimal `/poll` query with only two request keys:
{"requestKeys": [
"1zirlzrAQi4Zlzew5t8LF1jTtkom6YZS9qT-K9IEzHI",
"MdYI2HrYztPbpnAN5BXCT4IRw10XqcIU1qAPLC0l9Eo"
]}
which would return the empty JSON object.
Aside from all of that, the error handling for `internalPoll` is rather poor as it exists purely within `MaybeT`, giving no chance of reporting any meaningful errors. (I threw away a small cleanup for this since it was too debugging oriented, and needs to go through another round of …

service: return correct tx hash in txindex inner join

---

src/Chainweb/Pact/Backend/Compaction.hs

- only flush the logger handle if it's open. the flushing thread will throw an exception. this doesn't actually cause any issues, we just don't need to perform the flush if the handle is no longer open, and it prints some unnecessary/silly error messages to stderr.
- don't redundantly log the initial query to grab the latest block height on chain 0. this is confusing to look at, because users see the logs coming, and then nothing further.

Compaction: a couple of minor bug fixes

---

src/Chainweb/Version/Mainnet.hs

This restores the change made in #1529 which was reverted by #1550.

Move the shift to using Musl back to block height 2_939_323 (again)

---

src/Chainweb/Version.hs
test/Chainweb/Test/Orphans/Internal.hs
test/Chainweb/Test/Roundtrips.hs

```
❯ cabal run test:chainweb-tests -- --pattern "roundtrip tests.HasTextRepresentation roundtrips"
Chainweb Tests
Chainweb Unit Tests
roundtrip tests
HasTextRepresentation roundtrips
ChainwebVersionName:   OK
+++ OK, passed 100 tests.
ChainId:               OK
+++ OK, passed 100 tests.
BlockHash:             OK
+++ OK, passed 100 tests.
Seconds:               OK
+++ OK, passed 100 tests.
Micros:                OK
+++ OK, passed 100 tests.
Hostname:              OK
+++ OK, passed 100 tests.
Port:                  OK
+++ OK, passed 100 tests.
HostAddress:           OK
+++ OK, passed 100 tests.
T.Text:                OK
+++ OK, passed 100 tests.
[Char]:                OK
+++ OK, passed 100 tests.
PeerId:                OK
+++ OK, passed 100 tests.
Int:                   OK
+++ OK, passed …
```

fix HasTextRepresentation for Fork, add test

---

cabal.project

Summary: When running Template Haskell, GHC sees that some code it loads has dependent modules that also have a dependency on the zlib shared object via an `extra-libraries` clause; GHC can't find or load this module, issuing a warning, but it doesn't matter because the Template Haskell code doesn't actually *use* zlib despite having a transitive dependency on it.
Silence this warning, as it's *extremely* annoying to see while working on any files that use Template Haskell for any purposes e.g. deriving lenses.
Change-Id: I0ac0fe06ff0ff7fc40beb6f81b314374

cabal: stop giving superfluous warnings on missing shared libraries

---

bench/Chainweb/Pact/Backend/ForkingBench.hs

The idea is to prevent benchmarks from being so flaky in CI.

Raise block gas limit in ForkingBench

---

test/Chainweb/Test/Pact/RemotePactTest.hs

Spot the problem:
```
, after AllSucceed "poll bad key test" $
testCaseSteps "local preflight sim test" $ \step ->
join $ localPreflightSimTest <$> iot <*> cenv <*> pure step
, after AllSucceed "poll returns correct results" $
testCaseSteps "poll correct results test" $ \step ->
join $ pollingCorrectResults <$> iot <*> cenv <*> pure step
, after AllSucceed "webauthn signatures" $ testCase "webauthn sig" $ join $ webAuthnSignatureTest <$> iot <*> cenv
```
When we migrated to `sequentialTestGroup`, this test suite was mostly left untouched because I had assumed that we got a nice bit of concurrency from being a bit less sequential. Unfortunately, because we didn't use `sequentialTestGroup` here, while maintaining this code, it looks like we mistook `after` for `testGroup`, thinking the …

RemotePactTest fix

---

chainweb.cabal
src/Chainweb/Pact/Backend/Compaction.hs
test/Chainweb/Test/MultiNode.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/Utils.hs

`RemotePactTest.txlogsCompactionTest` is flaky without this and actually `compact-live-node` in `SlowTests` is sort of flaky as well.

Make compaction of live nodes retry until the db is available

---

src/Chainweb/Pact/Types.hs

The block gas limit is used to calculate the tx timeout, and tests can trigger it if there are noisy neighbors. This hopefully fixes that.

Raise test block gas limit to avoid spurious TxTimeouts during tests

---

chainweb.cabal
node/ChainwebNode.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Miner/Core.hs
test/Chainweb/Test/MultiNode.hs
test/Chainweb/Test/Utils.hs

This is another attempt at fixing the racy issue that's causing `RemotePactTest` to be flaky. I ran into a segfault while I was writing this, which was caused by closing the rocksdb while the node was still running, in turn caused by incorrect use of `async`.

Allow the node to communicate when it's ready to serve requests

---

src/Chainweb/VerifierPlugin/Hyperlane/Binary.hs
src/Chainweb/VerifierPlugin/Hyperlane/MessageERC20.hs
src/Chainweb/VerifierPlugin/Hyperlane/Utils.hs
test/Chainweb/Test/Pact/VerifierPluginTest/Transaction.hs

Changes:
- make capability's token message take base64 message instead of object
- add chainId to token message
- refactor tests to generate base64 manually

Change the MessageERC20 plugin's workflow with the token message.

---

src/Chainweb/Pact/Backend/Compaction.hs
src/Chainweb/WebPactExecutionService.hs
test/Chainweb/Test/Pact/PactMultiChainTest.hs
test/Chainweb/Test/Pact/Utils.hs

Without this, nodes fail on compacted dbs with something like this:
```
2024-02-15T22:42:02.653Z [Error] [chainwebVersion=mainnet01|peerId=hYiuKp|port=...|host=...|chain=7|component=pact|type=ChainwebApp] Received exception running pact service (syncToBlockBlock): {"tag":"PactInternalError","contents":"callDb (dbIndexTransactions): user error (error during batch insert: ErrorConstraint)"}
chainweb-node: {"tag":"PactInternalError","contents":"{\"tag\":\"PactInternalError\",\"contents\":\"callDb (dbIndexTransactions): user error (error during batch insert: ErrorConstraint)\"}"}
```
It would maybe be preferable if we just did an ordinary checkpointer rewind. #1794 is the cause.

Rewind TransactionIndex on compaction

---

src/Chainweb/Pact/Backend/Compaction.hs
test/Chainweb/Test/Pact/PactMultiChainTest.hs
test/Chainweb/Test/Pact/PactSingleChainTest.hs

The old code would not compact tables that were created in the past relative to the compaction height but never written to in the past.

fix: getVersionedTables based on VersionedTableCreation not VersionedTableMutation

---

src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/Configuration.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/Pact/Types.hs
test/Chainweb/Test/Pact/PactExec.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/Utils.hs
tools/cwtool/TxSimulator.hs

To prevent transactions with long table-scans from taking too long and backing up others.

service: implement timeout support for `/local` endpoints

---

test/ChainwebTests.hs

These two test suites seem to fail often, perhaps because when they run at the same time they conflict.
Change-Id: I6cb8714d0e60b798d30bab1dc23554ca4e2e372f

deflakify: run test suites which use full nodes sequentially

---

node/ChainwebNode.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/TransactionExec.hs
src/Chainweb/Pact/Types.hs
src/Chainweb/Version.hs
src/Chainweb/Version/Development.hs
src/Chainweb/Version/Guards.hs
src/Chainweb/Version/Mainnet.hs
src/Chainweb/Version/RecapDevelopment.hs
src/Chainweb/Version/Registry.hs
src/Chainweb/Version/Testnet.hs
test/Chainweb/Test/Cut/TestBlockDb.hs
test/Chainweb/Test/Pact/Checkpointer.hs
test/Chainweb/Test/Pact/PactMultiChainTest.hs
test/Chainweb/Test/Pact/TransactionTests.hs
test/Chainweb/Test/Pact/VerifierPluginTest/Transaction.hs
test/Chainweb/Test/TestVersions.hs

Adds "quirks", special one-off validation behaviors, to `ChainwebVersion`. Also some test cleanup and allows read-only replay to open rocksdb read-only.

Add quirks to ChainwebVersion

---

.github/workflows/applications.yml

Not sure why we used push:, but we do less CI overall if we use pull_request: and it seems to work better with merge queue.

Replace push: CI with pull_request: CI

---

src/Chainweb/Mempool/InMem.hs
src/Chainweb/Mempool/Mempool.hs
src/Chainweb/Pact/PactService/ExecBlock.hs
src/Chainweb/Pact/Validations.hs
test/Chainweb/Test/Pact/RemotePactTest.hs

This does not affect replay because transactions with invalid TTLs
never make it into blocks.
https://gerrit.aseipp.dev/q/I55818845ae3ecadcd6a4d258160d8033d0309322

feat(api)!: different errs for "ttl expired" and "tx in future"

---

src/Chainweb/Chainweb/PeerResources.hs
src/Chainweb/Pact/Backend/ChainwebPactDb.hs
src/Chainweb/Pact/Backend/Compaction.hs

Compaction to prior block heights should be equivalent to rewinding and then
compacting; this change makes that the implementation more or less, by adding
a rewind to the target before compaction of user tables. Note that it doesn't
change the compaction query itself, which is still compacting "to a height",
despite not really being necessary.
https://gerrit.aseipp.dev/q/I94b25354a18f8edf9daa729f23fe05704b0adbc4

Use checkpointer rewind in compaction

---

src/Chainweb/Mempool/InMem.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/PactInProcApi.hs
src/Chainweb/Utils.hs

Previously the number of replayed blocks was logged as (), which is not a number at all. Now, we log the number of blocks played, and even then, we avoid logging it if it doesn't exceed a reasonable fork size.
Also some logs are moved to debug level.
https://gerrit.aseipp.dev/q/I594d9500a5c1745f09a5375fc6a0a7e6f44c8807

Logging changes

---

test/Chainweb/Test/Pact/RemotePactTest.hs

As far as I can tell there's no reason to do this.
https://gerrit.aseipp.dev/q/I7dcc33adc4cf4a3f9d58d29f5e40920fb0a21b92

fix: stop grabbing the tx time before starting tests

---

test/ChainwebTests.hs

The Cut tests include a beefy quickcheck test which, if scheduled earlier, 
executes in parallel with other tests, speeding them up by ~10 seconds on my 
machine.
https://gerrit.aseipp.dev/q/I2c138cd183a382101a27602378e5bb940a9cc3f4

test: reorder tests so they're faster

---

src/Chainweb/Pact/Backend/RelationalCheckpointer.hs
test/Chainweb/Test/MultiNode.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Rosetta/RestAPI.hs
test/Chainweb/Test/Utils.hs

txlogsCompactionTest is somehow observing the pre-compaction
state when it looks at the txlogs sometimes, this is supposed
to fix that. It also makes our utils for running nodes take
their database dirs as parameters instead of having those utils
generate them.
https://gerrit.aseipp.dev/q/I6bd1aeec174836d12e753eb8e1b6cacbcb8ed431

tests: txlogsCompactionTest stops the node during compaction

---

.github/workflows/applications.yml

This lets gerrit trigger github CI by pushing to its own github branches for each change.
Every push really should have CI. The only reason we didn't was to avoid
duplicating CI for the merge queue; looks like there's a better way to do that.
This uses the "not-pattern" in 
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
Test plan: check that opening a github PR with this change triggers
CI, but that CI is labelled as "push" CI, then check that after merge, 
the merge queue doesn't duplicate CI, and gerrit's branches trigger CI
without a PR.

ci: enable CI on gerrit branch push

---

bench/Chainweb/Pact/Backend/Bench.hs
bench/Chainweb/Pact/Backend/ForkingBench.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/Configuration.hs
src/Chainweb/Pact/Backend/ChainwebPactDb.hs
src/Chainweb/Pact/Backend/PactState/GrandHash/Import.hs
src/Chainweb/Pact/Backend/RelationalCheckpointer.hs
src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/Pact/Types.hs
test/Chainweb/Test/MultiNode.hs
test/Chainweb/Test/Pact/Checkpointer.hs
test/Chainweb/Test/Pact/PactSingleChainTest.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Pact/Utils.hs
test/SlowTests.hs
tools/cwtool/TxSimulator.hs

This stops us writing rows to the database that are overwritten in the same block. Benchmarking says this isn't substantially faster, but it can save space.
This isn't safe to enable if you use Rosetta, which relies on these intermediate rows.
Change-Id: I88660fa4f0ee481e06808f66d98a86a3eb3722db

Do not persist intra-block writes

---

src/Chainweb/CutDB.hs

Otherwise we prune cuts at the wrong height;
we meant to prune cuts more than 5000 blocks old,
but now it's off by a factor of the number of chains.
https://gerrit.aseipp.dev/c/chainweb-node/+/181
Change-Id: Ic76f6efe7fe49a38c0254b64d583bb9dace6050e
---
- https://app.asana.com/0/0/1207195145181778

fix: fix cut pruning code dimensional analysis bug

---

test/Chainweb/Test/Pact/GrandHash.hs
test/Chainweb/Test/Pact/ModuleCacheOnRestart.hs
test/Chainweb/Test/Pact/PactReplay.hs
test/Chainweb/Test/Pact/PactSingleChainTest.hs
test/Chainweb/Test/Pact/RemotePactTest.hs
test/Chainweb/Test/Rosetta/RestAPI.hs
test/Chainweb/Test/Utils.hs
test/ChainwebTests.hs
test/SlowTests.hs

This slows the tests by 20s on my machine but is probably worth it
for iteration speed, because it lets run individual tests (or groups)
at our whim.
See https://github.com/UnkindPartition/tasty/issues/414 for background.
Change-Id: I4bd7f0ba24b29c4ce9bf18ea2842f57337c2dfa3
---
- https://app.asana.com/0/0/1207204425063992

tests: make sequential test groups still allow running select tests

---

.github/workflows/applications.yml
.github/workflows/macos.yaml
cabal.project

- fix haskell-actions (haskell/actions was deprecated)
- switch to macos-14-large to use x86_64 because `macOS-latest` is using arm runner which is broken for now (musl test)
- remove gnu-tar work around (was fixed in runners a long time ago)
- add new homebrew openssl paths

[CI]: Add homebrew paths to cabal.project for the recent macos-14 runners

---

cabal.project
default.nix
flake.lock
flake.nix

This requires some minor updates elsewhere because we have to update the flake lockfile. This will ensure the Nix builds match the current CI, which is 9.6.4 (and it will unbreak `devShell`, too.)

nix: update to ghc 9.6.4

---

CHANGELOG.md
changes/.gitignore
changes/2024-05-30T143223-0500.txt
make_change_file
tools/changelog/README.md
tools/changelog/create-entry
tools/changelog/rollup

This should be much easier and much more fullproof. As a bonus, we can stop doing the "Internal changes" section because the new `Commits` section will include everything anyway, leaving only user-visible entries in the `Changes` section.

changelog: add new `rollup` tool to automatically generate changelogs

---

changes/2024-05-30T145746-0400.txt
src/Chainweb/Logging/Config.hs
src/Chainweb/Utils.hs

Just to be clear for any readers: "telemetry" is structured logging for node operators to use to monitor their nodes. It is not sent to Kadena. By default, it is sent to stdout, and it can be configured to be sent to an Elasticsearch instance of the user's choosing.
This commit disables even logging telemetry to the terminal by default, because usually it's very verbose and not useful.
Change-Id: I83ed57c79fa99151909c76d7de70f6edc88106f8

log: disable telemetry backend by default

---

changes/2024-05-30T145629-0400.txt
node/ChainwebNode.hs

This has the nice side effect of also disabling the warning that RTS stats are disabled when telemetry is off, because RTS stats don't matter in that case.
Change-Id: I4111672ccc18760184d3325c0cd998c3c91fd6d2

log: disable top-level monitors when telemetry is disabled

---

changes/2024-05-30T145604-0400.txt
src/Chainweb/Chainweb.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/BlockValidation.hs
src/Chainweb/Pact/Service/Types.hs
src/Chainweb/WebPactExecutionService.hs
test/Chainweb/Test/MultiNode.hs

Change-Id: I808d5799db1639b45945fe36ffbd1762f070b734

feat: When ro-replay upper bound is unset use latest checkpointer block

---

changes/2024-05-30T144824-0400.txt
src/P2P/TaskQueue.hs

P2P task failures that are followed by retries aren't very interesting, but if they're past the retry limit that's more interesting.
Change-Id: I982be55277f5637be4c28df1320f9643d1a9a064

log: P2P task failures are logged at Debug, not Info

---

src/Chainweb/Version/Mainnet.hs

We have another quirk for an earlier block, but this one never made it in, 
because no nodes on mainnet had had issues at the time. However, one user 
has had issues with it recently, hence the change.

fix: add extra quirk to block 4594049, fixing catchup for some nodes

---

changes/2024-05-30T163404-0400.txt
src/Chainweb/Chainweb/PeerResources.hs
src/Chainweb/NodeVersion.hs
src/Chainweb/Utils.hs
src/P2P/Node.hs

Change-Id: I4db5f0feb0e72619bdc2476fc70184a6f166edda

log: Clean up P2P logs

---

.github/workflows/nix.yml
flake.lock

This upgrades our `hackage`/`hs-nix-infra` inputs to the Flake as a8c075e732f577cef849ac0b502ab1eefc77d853 broke it with the `http2` bound.
It also updates our GHA runners to use a newer version of Nix, as we were running into a bug inside Nix which made errors nearly impossible to understand (see https://github.com/ccornix/groundzero/commit/a5055f2be8a4c832295bfd8b53834620bb90b829)

nix: fix build

---

changes/2024-05-30T144952-0400.txt
src/Chainweb/Pact/PactService.hs

Change-Id: Id2d597d6e72b0bbd6825184b9dd122261502d035

log: log rewinds in execValidateBlock instead of blocks played

---

changes/2024-06-11T102857-0500.txt
changes/2024-06-11T104051-0500.txt
node/ChainwebNode.hs
src/Chainweb/Graph.hs
src/Chainweb/NodeVersion.hs
src/Chainweb/RestAPI/NodeInfo.hs
src/Chainweb/Utils/Rule.hs
src/Chainweb/Version.hs
src/Chainweb/Version/Development.hs
src/Chainweb/Version/Mainnet.hs
src/Chainweb/Version/RecapDevelopment.hs
src/Chainweb/Version/Testnet.hs
test/Chainweb/Test/Orphans/Internal.hs
test/Chainweb/Test/TestVersions.hs
tools/ea/Ea/Genesis.hs

Change-Id: I7999b4200ce823be0a0466291852d159824cc16f

expand info endpoint with more information

---

changes/2024-06-19T182508-0400.txt
node/ChainwebNode.hs

This makes telemetry more reliable in the case of stalls and also much less expensive in terms of disk space.
Change-Id: I28b5efa9d89323b1e381c1bd9085e46fb9afb040

log: telemetry log current cut periodically, instead of on changes

---

changes/2024-06-19T182544-0400.txt
src/Chainweb/Pact/PactService.hs

Shows a time estimate now as well as a smoother estimated rate.
Change-Id: I2839ccab331ef9493d7059af598930372ffdf6b9

log: better progress for read-only replay

---

changes/2024-06-19T182722-0400.txt
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/Service/PactQueue.hs

I don't understand why this fixes the issue, but it is actually a correct thing to do; this PR just makes sure that we are masked when we fork off the Pact task thread.
Change-Id: I98ac853da9efd086be749d388a5eb559f7866af0

fix: make ctrl-C work for replays (and perhaps more generally)

---

.github/workflows/applications.yml

* fixes docker tag when invoking integration tests to account for -frozen (this fixes non-running tests)
* Uses github app generated token to identify test run
* Waits for tests to run to finish build; failing tests will cause the calling step to fail
---
- https://app.asana.com/0/0/1207791393032892

Improve integration test call

---

src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/Configuration.hs
src/Chainweb/RestAPI.hs
src/Chainweb/Rosetta/RestAPI.hs
src/Chainweb/Rosetta/RestAPI/Server.hs
src/Chainweb/Rosetta/Utils.hs
test/Chainweb/Test/Rosetta/RestAPI.hs

The current Rosetta implementation makes unsound assumptions about the format and ordering of internal database logs. The Rosetta test suite also relies on unstable `Hashable` instances and the implied ordering of values in several places. This makes it unfeasible to maintain the implementation without compromising test coverage and soundness.
This PR deprecates Rosetta:

deprecate rosetta

---

src/Chainweb/Chainweb/CheckReachability.hs
src/Chainweb/Utils/RequestLog.hs

Logs response size with requestResponseLogger, after the response completes. If the response doesn't complete, we still log it as it goes out if it's large.

response size logging

---

src/Chainweb/BlockHeader/Internal.hs
src/Chainweb/RestAPI/NodeInfo.hs
src/Chainweb/Utils/Rule.hs
src/Chainweb/Version.hs
src/Chainweb/Version/Development.hs
src/Chainweb/Version/Guards.hs
src/Chainweb/Version/Mainnet.hs
src/Chainweb/Version/RecapDevelopment.hs
src/Chainweb/Version/Testnet.hs
src/Chainweb/Version/Utils.hs
test/lib/Chainweb/Test/Orphans/Internal.hs
test/lib/Chainweb/Test/TestVersions.hs
test/unit/Chainweb/Test/Version.hs

This generalizes the "measurement" idea so that measurements of rules are represented by zippers, allowing the caller to navigate around a measurement themselves.
---
- https://app.asana.com/0/0/1208701053549686

Make RuleZipper to replace Measurement

---

src/Chainweb/Chainweb.hs

It's extra latency that doesn't get us anything.

stop going through PactService to pre-insert check an empty tx batch 

---

src/P2P/Node.hs

Should be faster than using the Foldable `length` because it's using the default impl

compute peerCount using ixset's size function

---

src/P2P/Node.hs
src/P2P/Node/PeerDB.hs
test/lib/Chainweb/Test/Orphans/Internal.hs

We randomize the peer ordering by assigning a peer a random number that is used subsequently to order it with respect to other peers upon request from the /peer GET endpoint.
An alternative of generating a seed on startup that would be used to "salt" the peer ordering was considered but ran into implementation difficulties and seems equivalent.
---
- https://app.asana.com/0/0/1208677746463529

randomized peer ordering

---

src/Chainweb/Pact/PactService/ExecBlock.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/Validations.hs
test/lib/Chainweb/Test/Pact/Utils.hs
test/unit/Chainweb/Test/Pact/RemotePactTest.hs

Change-Id: Ifbad9a2e9c28810f34b80a6c02cc08d68c955cff

add error messages for assertCommand failures in pact api

---

README.md
cabal.project
chainweb.cabal
src/Chainweb/Block.hs
src/Chainweb/BlockHeader.hs
src/Chainweb/BlockHeader/Internal.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Mempool/InMem.hs
src/Chainweb/Pact/Backend/Compaction.hs
src/Chainweb/Pact/Backend/Utils.hs
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/PactService/Checkpointer/Internal.hs
src/Chainweb/Pact/PactService/Pact5/ExecBlock.hs
src/Chainweb/Pact/Types.hs
src/Chainweb/Pact4/Backend/ChainwebPactDb.hs
src/Chainweb/Pact4/TransactionExec.hs
src/Chainweb/Pact5/Backend/ChainwebPactDb.hs
src/Chainweb/Pact5/TransactionExec.hs
src/Chainweb/Rosetta/Internal.hs
src/Chainweb/Version.hs
src/Chainweb/Version/Mainnet.hs
src/Chainweb/Version/RecapDevelopment.hs
src/Chainweb/Version/Registry.hs
src/Chainweb/Version/Testnet04.hs
test/lib/Chainweb/Test/TestVersions.hs

Address review. These commits are meant to be reviewed individually.

pact5 review phase 1

---

src/Chainweb/Utils.hs
test/unit/Chainweb/Test/Pact5/CutFixture.hs
test/unit/Chainweb/Test/Pact5/RemotePactTest.hs
test/unit/Chainweb/Test/Rosetta/RestAPI.hs

Rosetta's RestAPI errors have some kind of issue with them right now, which is helped by adding a `HasCallStack` constraint to this assertion function.

Add HasCallStack to help debugging Rosetta errors

---

test/unit/Chainweb/Test/Pact5/RemotePactTest.hs

Also added a `fail` PT which I may backport to property-matchers. Also made `sending`'s exception include the response body specifically.

Add Pact5.RemotePactTest.invalidTxsTest

---

chainweb.cabal
src/Chainweb/BlockHash.hs
src/Chainweb/BlockHeader.hs
src/Chainweb/BlockHeader/Internal.hs
src/Chainweb/BlockHeaderDB/Internal.hs
src/Chainweb/BlockPayloadHash.hs
src/Chainweb/ChainId.hs
src/Chainweb/MinerReward.hs
src/Chainweb/Pact/Backend/Compaction.hs
src/Chainweb/Pact/PactService/Pact4/ExecBlock.hs
src/Chainweb/Pact/PactService/Pact5/ExecBlock.hs
src/Chainweb/Payload.hs
src/Chainweb/Ranked.hs
src/Chainweb/Utils.hs
test/unit/Chainweb/Test/MinerReward.hs
test/unit/Chainweb/Test/Pact4/RewardsTest.hs
test/unit/ChainwebTests.hs

A number of small unrelated changes. It is easiest to review on a per commit basis.

miscelaneous small changes

---

src/Chainweb/BlockHeader.hs
src/Chainweb/BlockHeader/Internal.hs
src/Chainweb/ChainId.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Crypto/MerkleLog.hs
src/Chainweb/MerkleUniverse.hs
src/Chainweb/MinerReward.hs
src/Chainweb/Pact/Types.hs
src/Chainweb/Utils/Serialization.hs
src/Chainweb/WebPactExecutionService.hs
src/Data/PQueue.hs
src/P2P/TaskQueue.hs

Several small changes that will keep some upcoming larger code reviews more concise: 
* add binary, textual, and JSON encodings for `MinerReward`
* improve fix some code comments
* Add `HasChainwebVersion` and `HasChainId` instances for `BlockInProgress` and `NewBlock`
* Generalize `atChain` to accept `HasChainId` constraint
* add `putShortByteString` and `getShortByteString` to serialization utils
* fix indentation of some code in `Chainweb.Chainweb`
* add `parentHeaderHash` and `rankedParentHash` functions for `BlockHeader`

miscellaneous small changes

---

src/Chainweb/Mempool/InMem.hs
src/Chainweb/Mempool/Mempool.hs
src/Chainweb/Mempool/RestAPI/Client.hs
src/Chainweb/Pact/PactService/Pact4/ExecBlock.hs
src/Chainweb/Pact/PactService/Pact5/ExecBlock.hs
src/Chainweb/Pact/RestAPI/Server.hs
test/unit/Chainweb/Test/Pact4/RemotePactTest.hs
test/unit/Chainweb/Test/Pact5/RemotePactTest.hs

Change-Id: I435856410fb82c59f8170d32bf12e5cea69833d1

add a mempool insertCheck variant that doesn't short-circuit. improve error messages in /send api

---

node/src/ChainwebNode.hs
src/Chainweb/BlockWeight.hs
src/Chainweb/Difficulty.hs

This allows it to be more easily ingested by ElasticSearch.
Change-Id: Id0000000010fc50d9363200a7d4ea8c251a2f25a
---
- https://app.asana.com/0/0/1209151718815716

Include difficulty as Double in BlockUpdate telemetry

---

cabal.project
chainweb.cabal
pact/pact5/coin-contract/coin.repl
pact/pact5/namespaces/ns.repl
pact/pact5/namespaces/v1/ns.repl
test/unit/Chainweb/Test/Pact5/TransactionTests.hs
test/unit/ChainwebTests.hs

- Add repl test support
- Do not run old coin repl tests that no longer apply to pact 5

Add Pact 5 transaction tests

---

src/Chainweb/Utils/RequestLog.hs

Because of a bug in request logging on the debug log level specifically when telemetry is enabled, all request bodies delivered to chainweb have their contents repeated infinitely. 
Change-Id: Id0000000fcfba9b9c67184fc89a07944f416f739

Fix request logging on Debug log level

---

libs/chainweb-storage/src/Chainweb/Storage/Table/RocksDB.hs
test/lib/Chainweb/Test/Cut.hs
test/lib/Chainweb/Test/Cut/TestBlockDb.hs
test/lib/Chainweb/Test/Pact4/Utils.hs
test/lib/Chainweb/Test/Pact4/VerifierPluginTest/Transaction.hs
test/lib/Chainweb/Test/Pact4/VerifierPluginTest/Transaction/Message/After225.hs
test/lib/Chainweb/Test/Pact4/VerifierPluginTest/Transaction/Message/Before225.hs
test/lib/Chainweb/Test/Pact5/Utils.hs
test/lib/Chainweb/Test/Utils.hs
test/unit/Chainweb/Test/Pact4/ModuleCacheOnRestart.hs
test/unit/Chainweb/Test/Pact4/PactMultiChainTest.hs
test/unit/Chainweb/Test/Pact4/PactSingleChainTest.hs
test/unit/Chainweb/Test/Pact4/SPV.hs
test/unit/Chainweb/Test/Pact4/VerifierPluginTest.hs
test/unit/Chainweb/Test/Pact5/CutFixture.hs
test/unit/Chainweb/Test/Pact5/PactServiceTest.hs
test/unit/Chainweb/Test/Pact5/TransactionExecTest.hs
test/unit/ChainwebTests.hs

This makes our rocksdb smaller, which makes certain tests faster, especially the Cut property tests like meetAssociative which mine a lot of blocks.
Change-Id: Id000000077e9012e622fc8577efd411f2fbb3993

Use deleteRange to clean up testRocksDb

---

src/Chainweb/Pact/PactService.hs

For some reason, I reverted execReadOnlyReplay to stop using CheckablePayloadWithOutputs, which makes the errors very hard to use, because there's no "expected" output printed.
Change-Id: Id00000002157778ccb796c0ebee738d431edc4b5

Fix replay BVF errors

---

src/Chainweb/Pact4/Types.hs

This must've been from early work in Pact 5 integration, which we didn't spot because we weren't doing normal mainnet replays, just parity replays.
Change-Id: Id0000000b119e36484da926eaf598f98ecc885e2

Stop including unknown errors in outputs

---

cabal.project.freeze

I have no idea why cabal freeze doesn't do this, because I'm using cabal 3.12, but it's *required* to use multi-repl, and thus multicomponent in HLS.
Change-Id: Id000000002414c895259bf7f3152077affd40e59

Put Cabal 3.12.1.0 back in the freeze file

---

src/Chainweb/Pact/Backend/InMemDb.hs
src/Chainweb/Pact/Backend/Types.hs
src/Chainweb/Pact/Backend/Utils.hs
src/Chainweb/Pact/PactService/Checkpointer/Internal.hs
src/Chainweb/Pact4/Backend/ChainwebPactDb.hs
src/Chainweb/Pact5/Backend/ChainwebPactDb.hs
test/unit/Chainweb/Test/Pact4/Checkpointer.hs
test/unit/Chainweb/Test/Pact4/PactSingleChainTest.hs
test/unit/Chainweb/Test/Pact5/CheckpointerTest.hs
test/unit/Chainweb/Test/Pact5/TransactionExecTest.hs

NoSuchTable is a new Pact error case as of Pact 5, but we never throw it. Instead, when a table is missing, sqlite throws an exception, and this is recorded as an "unknown database error" by Pact. But we can easily throw it, as shown here, and simultaneously clean up some of the more repetitious and error-prone conditionals in Pact 5's ChainwebPactDb.
Change-Id: Id000000030817f20e355d569ca29864db3d777cf

Produce NoSuchTable Pact error, and clean up ChainwebPactDb

---

src/Chainweb/Pact/PactService.hs
test/multinode/MultiNodeNetworkTests.hs

This case is exclusive to restarting a node after a Pact 5 transition:
we're still running the Pact 4 initialization code when we start a
Pact 5 node, which causes a crash.
Change-Id: Id0000000d523a8dc8809e5ff12ae7bb53f82f393

Fix restarting after Pact 5 transition

---

bench/Chainweb/Utils/Bench.hs
cabal.project
src/Chainweb/Pact/PactService.hs
src/Chainweb/Pact/RestAPI/Server.hs
src/Chainweb/Pact/Types.hs
test/lib/Chainweb/Test/Utils.hs
test/unit/Chainweb/Test/Pact5/HyperlanePluginTests.hs
test/unit/Chainweb/Test/Pact5/RemotePactTest.hs
test/unit/Chainweb/Test/Pact5/TransactionExecTest.hs

This provides us with a more compatible format for errors in CommandResults, avoiding some breakage to wallets, in particular Chainweaver.
Change-Id: Id0000000525b3f854ef3d89b28a22593fcc39612

Update to newer Pact 5

---

src/Chainweb/Pact5/Backend/ChainwebPactDb.hs

Straightforward algorithmic optimization, owing to the fact that we will usually have more keys for a table in the database than we'll have pending rows for the table in memory.
Change-Id: Id00000007b294fb0f5c33d185109df33f1d88bfa

Attempt to optimize doKeys

---

test/unit/Chainweb/Test/Pact5/TransactionExecTest.hs

Because _crResult is more important, we should assert on it first.
Change-Id: Id00000007a5762c813b59dcca9020168b46d4fda

Reorder asserts in TransactionExecTest

---

chainweb.cabal
src/Chainweb/BlockHeaderDB/RemoteDB.hs
src/Chainweb/Pact/Mempool/InMem.hs
src/Chainweb/Pact4/SPV.hs
src/Chainweb/VerifierPlugin/Hyperlane/Message/After225.hs

This PR removes the `errors` package. We rely on two helpers:
- `hush`
- `note`
which can be easily integrated into our codebase.

remove `errors` package

---

src/Chainweb/BlockHeaderDB.hs
src/Chainweb/BlockHeaderDB/Internal.hs
src/Chainweb/BlockHeaderDB/RemoteDB.hs
src/Chainweb/BlockHeaderDB/RestAPI/Server.hs
src/Chainweb/CutDB.hs
src/Chainweb/Sync/WebBlockHeaderStore.hs
src/Chainweb/TreeDB.hs

Add a `TreeDB` instance `RankedBlockHeader`. This `RankedBlockHeaderDB` is strictly more efficient than the current `BlockHeaderDB` and by implementing the latter in terms of the former, the performance of the current `BlockHeaderDB` is improved, too.
The ranked version should be preferred whenever possible, which is subject to an upcoming PR. We may even consider renaming `BlockHeaderDB` into `UnrankedBlockHeaderDB` and `RankedBlockHeaderDB` into `BlockHeaderDB`. The unranked version should be used only to provide legacy API endpoints of the service API.
This PR also reverts the type of `lookup` and `lookupRanked` back to returning a maybe `Maybe`, while retaining improved error reporting in other parts. In practice, the `Either` value was redundant for improved error handling. The left …

Add RankedBlockHeaderDB and simplify TreeDB a bit

---

chainweb.cabal
src/Chainweb/BlockHeader/Internal.hs
src/Chainweb/Chainweb/ChainResources.hs
src/Chainweb/Pact/Backend/ChainwebPactDb.hs
src/Chainweb/Pact/Backend/Compaction.hs
src/Chainweb/Pact/Backend/PactState.hs
src/Chainweb/Pact/Backend/Utils.hs
src/Chainweb/Pact4/Backend/ChainwebPactDb.hs
src/Chainweb/PayloadProvider/Pact.hs
src/Chainweb/PayloadProvider/Pact/BlockHistoryMigration.hs
test/blockhistory-migration/BlockHistoryMigrationTests.hs
test/unit/Chainweb/Test/Pact/BlockHistoryMigrationTest.hs
test/unit/ChainwebTests.hs

Migrate BlockHistory table to add missing column for the new payload design.
Specifically:
- Constraints such as the uniqueness of the blockhash column must be satisfied at the time the column is added.
- SQLite does not allow adding columns with unique constraints via ALTER TABLE (see [SQLite docs](https://www.sqlite.org/lang_altertable.html)).
This PR introduces a migration that:
- Runs only if tableNeedsMigration indicates it’s required.
- Performs a row-wise migration of existing data from the old BlockHistory table and the BlockHeaderDb (backed by RocksDB).
- Migrates data in chunks of 10,000 entries, each chunk committed in its own transaction for safety and performance.
**Note**
The migration module is temporary and can be removed once all deployments have successfully migrated.

add blockhistory migration

---

.github/workflows/applications.yml
chainweb.cabal
cwtools/cwtools.cabal
cwtools/standalone-pruner/Main.hs
node/src/ChainwebNode.hs
src/Chainweb/BlockHeaderDB/PruneForks.hs
src/Chainweb/Chainweb.hs
src/Chainweb/Chainweb/Configuration.hs
src/Chainweb/Chainweb/CutResources.hs
src/Chainweb/Utils.hs
src/Chainweb/WebBlockHeaderDB.hs
test/lib/Chainweb/Test/MultiNode.hs
test/lib/Chainweb/Test/Utils.hs
test/unit/Chainweb/Test/BlockHeaderDB/PruneForks.hs
test/unit/Chainweb/Test/CutDB.hs
test/unit/Chainweb/Test/TreeDB.hs
test/unit/ChainwebTests.hs

Updates the existing pruning algorithm to operate on multiple chains in lockstep to avoid dangling references and to be possible to interrupt and later resume, as well as run periodically and incrementally.

Multi-chain incremental pruning

---

src/Chainweb/Pact/Backend/ChainwebPactDb.hs

Otherwise, existing pact databases will trigger rewinds to genesis, because they will see no current ConsensusState rows.

Use BlockHistory if ConsensusState table is empty
